src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>area__c</fullName>
        <label>区域</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>clientlevel__c</fullName>
        <label>客户级别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公司VIP</fullName>
                </value>
                <value>
                    <fullName>部门VIP</fullName>
                </value>
                <value>
                    <fullName>普通客户</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>firstclassify__c</fullName>
        <label>客户一级分类</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>集团民营</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E7XU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>installationdate__c</fullName>
        <label>安装日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ismain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否主设备</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantySatart__c</fullName>
        <inlineHelpText>第一次装机后，根据验收时间自动默认保修开始日期</inlineHelpText>
        <label>设备保修开始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Warranty__c.object
<CustomObject>
    <fields>
        <fullName>Warrantyenddate__c</fullName>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warrantystartdate__c</fullName>
        <label>保修起始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <label>#区域#old</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北区</fullName>
                </value>
                <value>
                    <fullName>东区</fullName>
                </value>
                <value>
                    <fullName>南区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保修合约</relationshipLabel>
        <relationshipName>Fns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>serviceperiod__c</fullName>
        <label>保修年限（隐藏）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>全保</fullName>
                </value>
                <value>
                    <fullName>技术保修</fullName>
                </value>
                <value>
                    <fullName>单次付费</fullName>
                </value>
                <value>
                    <fullName>半保-不含激光腔</fullName>
                </value>
                <value>
                    <fullName>Credit code服务费</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>保修合约</label>
    <nameField>
        <label>合约名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>保修合约</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Warrantyproduct__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>合约产品</relationshipLabel>
        <relationshipName>sBw2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warranty__c</fullName>
        <label>合约</label>
        <referenceTo>Warranty__c</referenceTo>
        <relationshipLabel>合约产品</relationshipLabel>
        <relationshipName>tfsT</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Warrantyenddate__c</fullName>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warrantystartdate__c</fullName>
        <label>保修开始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <formula>TEXT(Equipment__r.warrantytype__c )</formula>
        <label>#设备保修类型</label>
        <type>Text</type>
    </fields>
    <label>合约产品</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>合约产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SchedulableEquipmentChance_Test.cls
/**
*Create By:Jmark
*TIME：2016年9月14日10:22:38
*Descripe:设备保修到期后自动生成对应的新的业务机会，提前一年通知，并增加提醒功能
 */
@isTest
private class SchedulableEquipmentChance_Test {

    static testMethod void myUnitTest() {
        Test.StartTest();
        Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        UserRole ur=new UserRole(); 
		ur.Name='01-总经理'; 
		insert ur; 
		User u=new User(); 
		u.FirstName='李'; 
		u.LastName='四'; 
		u.Alias='李四'; 
		u.Username='lisi@frensworkz.com'; 
		u.Email='lisi@frensworkz.com'; 
		u.CommunityNickname='lisi'; 
		u.UserRoleId=ur.Id; 
		u.ProfileId=profile.Id; 
		u.TimeZoneSidKey='Asia/Shanghai'; 
		u.LocaleSidKey='en_AU'; 
		u.EmailEncodingKey='UTF-8'; 
		u.LanguageLocaleKey='en_US'; 
		insert u; 
		Account acc=new Account();
		acc.Name='momo医院';
		acc.firstclassify__c='国有医院';
		acc.area__c='北区';
		acc.secondperson__c=u.Id;
		acc.clientlevel__c='公司VIP';
		insert acc;
		Equipment__c equ=new Equipment__c();
		equ.Name='cesixulihao';
		equ.warrantytype__c='全保';
		equ.customer__c=acc.Id;
		equ.ismain__c=true;
		equ.installationdate__c=Date.newInstance(2014, 4, 5);
		equ.warrantySatart__c=Date.today();
		equ.warrantyEnd__c=Date.today().addMonths(3);
		equ.OwnerId = u.Id;
		insert equ;
		Warranty__c wty=new Warranty__c();
		wty.Name='测试保修合约';
		wty.warrantytype__c='全保';
		wty.serviceperiod__c='3年';
		wty.customer__c=acc.Id;
		wty.area__c='北区';
		insert wty;
		Warrantyproduct__c war=new Warrantyproduct__c();
		war.Equipment__c=equ.Id;
		war.Warranty__c=wty.Id;
		war.Warrantyenddate__c=Date.today().addDays(365);
		war.Warrantystartdate__c=Date.today();
		insert war;
		SchedulableEquipmentChance srtc=new SchedulableEquipmentChance();
		string ch1='0 30 9 * * ?';
        System.schedule('自动计算设备机龄测试',ch1,srtc);
        Test.stopTest();
    }
}