src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>职务</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>准分子</fullName>
                </value>
                <value>
                    <fullName>飞白</fullName>
                </value>
                <value>
                    <fullName>路视</fullName>
                </value>
                <value>
                    <fullName>欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+路视</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalRepresentative__c</fullName>
        <label>法定代表人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>福州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CustomObject18__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>销售机会</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>销售机会产品</relationshipLabel>
        <relationshipName>Field1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>产品状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>跟进</fullName>
                </value>
                <value>
                    <fullName>赢单</fullName>
                </value>
                <value>
                    <fullName>丢单</fullName>
                </value>
                <value>
                    <fullName>中断</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThrowReason__c</fullName>
        <label>丢单原因</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>价格</fullName>
                </value>
                <value>
                    <fullName>品牌</fullName>
                </value>
                <value>
                    <fullName>客户关系</fullName>
                </value>
                <value>
                    <fullName>项目中断</fullName>
                </value>
                <value>
                    <fullName>策略及打包</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>预计成交单价（元）</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Currency</type>
    </fields>
    <label>销售机会产品</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>销售机会产品编码</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>销售机会产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessOpportunityApprovalStatus__c</fullName>
        <label>销售机会审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessSource__c</fullName>
        <label>商机来源</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>专家推荐</fullName>
                </value>
                <value>
                    <fullName>学术会议</fullName>
                </value>
                <value>
                    <fullName>主动拜访</fullName>
                </value>
                <value>
                    <fullName>渠道</fullName>
                </value>
                <value>
                    <fullName>内部交流</fullName>
                </value>
                <value>
                    <fullName>网路信息</fullName>
                </value>
                <value>
                    <fullName>同行交流</fullName>
                </value>
                <value>
                    <fullName>竞品预警</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                    <label>线索池</label>
                </value>
                <value>
                    <fullName>客户资产</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessType__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>是否是大项目</inlineHelpText>
        <label>商机类型</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>市/区</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <formula>Owner.LfourDepartment__c</formula>
        <label>销售机会所有人四级部门</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>最终用户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>销售机会</relationshipLabel>
        <relationshipName>FinalCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcurementMethod__c</fullName>
        <label>采购方式</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>院内采购</fullName>
                </value>
                <value>
                    <fullName>招投标</fullName>
                </value>
                <value>
                    <fullName>融资租赁</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>省/直辖市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOpportunityStatus__c</fullName>
        <label>销售机会关闭状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>丢单</fullName>
                </value>
                <value>
                    <fullName>中断</fullName>
                </value>
                <value>
                    <fullName>赢单</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeInstallation__c</fullName>
        <inlineHelpText>例如：全款已付，预计12月19日安装。</inlineHelpText>
        <label>预计装机日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jdxspzt__c</fullName>
        <label>阶段性审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityStatusTriggerTest.cls
@isTest
public class OpportunityStatusTriggerTest {
	@istest(SeeAlldata=true)
    static void test () {
        
     Account acc  =  new Account() ; 
     acc.Name = 'kehu';
     acc.city__c = '福州市';
     acc.province__c = '福建省';
     acc.Cunty__c = '1' ;
     acc.LegalRepresentative__c = '1';
     acc.Duty__c = '1' ;
     acc.ContactNumber__c = '123'; 
     acc.Gender__c = '男';
     insert acc ;
     
     Opportunity opp = new Opportunity();
	 opp.Name = '11222';
	 opp.StageName = '成交阶段';
	 opp.Amount = 0.0;
	 opp.Probability = 10.0;
	 opp.CloseDate = Date.newInstance(2018,08,13);
	 opp.CurrencyIsoCode = 'CNY';
	 opp.ProcurementMethod__c = '院内采购';
	 opp.BusinessSource__c = '专家推荐';
	 //opp.BusinessType__c = false;
	 opp.FinalCustomer__c = acc.id;
	 opp.BusinessOpportunityApprovalStatus__c = '已审批';
	 opp.jdxspzt__c = '草稿';
     opp.SalesOpportunityStatus__c ='中断';
	 opp.TimeInstallation__c = Date.newInstance(2018,08,13);
     insert opp;
        
     CustomObject18__c  cu = new CustomObject18__c();
     cu.Field1__c = opp.Id;
     cu.Amount__c = 1 ;
     cu.UnitCost__c = 1 ;
     cu.State__c ='赢单';
     insert cu;
     
     opp.SalesOpportunityStatus__c ='赢单';
     update  opp ;
    }
    @istest(SeeAlldata=true)
    static void test2 () {
        
     Account acc  =  new Account() ; 
     acc.Name = 'kehu';
     acc.city__c = '福州市';
     acc.province__c = '福建省';
     acc.Cunty__c = '1' ;
     acc.LegalRepresentative__c = '1';
     acc.Duty__c = '1' ;
     acc.ContactNumber__c = '123'; 
     acc.Gender__c = '男';
     insert acc ;
     
     Opportunity opp = new Opportunity();
	 opp.Name = '11222';
	 opp.StageName = '潜在阶段';
	 opp.Amount = 0.0;
	 opp.Probability = 10.0;
	 opp.CloseDate = Date.newInstance(2018,08,13);
	 opp.CurrencyIsoCode = 'CNY';
	 opp.ProcurementMethod__c = '院内采购';
	 opp.BusinessSource__c = '专家推荐';
	 opp.BusinessType__c = false;
	 opp.FinalCustomer__c = acc.id;
	 opp.BusinessOpportunityApprovalStatus__c = '草稿';
	 opp.jdxspzt__c = '草稿';
     opp.SalesOpportunityStatus__c ='丢单';
     opp.ThrowReason__c = '价格';
	 opp.TimeInstallation__c = Date.newInstance(2018,08,13);
     insert opp;
        
     CustomObject18__c  cu = new CustomObject18__c();
     cu.Field1__c = opp.Id;
     cu.Amount__c = 1 ;
     cu.UnitCost__c = 1 ;
     cu.State__c ='赢单';
     insert cu;
    }
}