src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>职务</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>准分子</fullName>
                </value>
                <value>
                    <fullName>飞白</fullName>
                </value>
                <value>
                    <fullName>路视</fullName>
                </value>
                <value>
                    <fullName>欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+路视</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalRepresentative__c</fullName>
        <label>法定代表人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>福州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>TEXT(customer__r.city__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>客户：市</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备使用状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>正常使用</fullName>
                    <default>true</default>
                    <label>正常使用</label>
                </value>
                <value>
                    <fullName>退换货</fullName>
                </value>
                <value>
                    <fullName>报废</fullName>
                </value>
                <value>
                    <fullName>停用</fullName>
                </value>
                <value>
                    <fullName>已销售</fullName>
                </value>
                <value>
                    <fullName>注册样机</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>H1io</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/polling__c.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>巡检</relationshipLabel>
        <relationshipName>OPjq</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>巡检</label>
    <nameField>
        <displayFormat>P-{0000000000}</displayFormat>
        <label>编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>巡检</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/product__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>单价</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>#产品</label>
    <nameField>
        <label>产品编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>approvestate__c</fullName>
        <label>出差审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                </value>
                <value>
                    <fullName>审批中</fullName>
                    <default>true</default>
                    <label>审批中</label>
                </value>
                <value>
                    <fullName>审批结束</fullName>
                </value>
                <value>
                    <fullName>拒绝</fullName>
                </value>
                <value>
                    <fullName>调回</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isupgrade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否升级</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/pollingTriggerTest.cls
@isTest
private class pollingTriggerTest {

    @istest(SeeAlldata=true)
    static void testpollingTrigger ()
    
    {
     Account acc  =  new Account() ; 
       acc.Name = 'kehu';
       acc.city__c = '福州市';
       acc.province__c = '福建省';
       acc.Cunty__c = '1' ;
       acc.LegalRepresentative__c = '1';
       acc.Duty__c = '1' ;
       acc.ContactNumber__c = '123'; 
       acc.Gender__c = '男';
     insert acc ;
     
     product__c pro = new product__c();
     pro.Name = '123';
     insert pro ;
     
     Equipment__c  eq = new Equipment__c();
     eq.Name = '123';
     eq.customer__c = acc.Id;
     eq.warrantytype__c ='保外';
     insert eq;
     
    /**servicerequest__c servicerequest = new servicerequest__c(
    OwnerId = '0056F0000082F6LQAU',
    Name = '123123',
    CurrencyIsoCode = 'CNY',
    RecordTypeId = '01290000000mqmoAAA',
    
    approvestate__c = '草稿',
    isupgrade__c = false,
    customer__c = acc.Id ,
    requesttime__c = Date.newInstance(2018,07,09),
    Field1__c = '保内免费',
    Field2__c = '准分子设备',
    Equipment__c = pro.Id,
    Field8__c = false);**/

    //insert servicerequest ;
      servicerequest__c   ser  = new servicerequest__c();
      ser.Name = 'aa';
      ser.requesttime__c = Date.newInstance(2018,07,09);
      ser.Field2__c ='准分子设备';
      ser.customer__c =acc.Id;
      ser.Equipment__c = eq.id ;
      insert ser ;
      
      
      
      polling__c poll = new polling__c();
   poll.pollingdate__c = Date.newInstance(2018,07,09);
   poll.Accunt1__c = acc.id;
   poll.DeviseSerialNumber__c = eq.id;
   poll.RecordTypeId = '0126F0000019If7QAE';
   poll.RespondingSpeed__c = '1';
   poll.ServiceAttitude__c = '3';
   poll.SolveEfficiency__c = '3';
   poll.QuotationFees__c = '2';
   poll.FieldSpecification__c = '4';
   poll.RespondingSpeed__c='3';
   poll.servicerequest__c=ser.Id ;
   insert  poll;
   
   
   poll.FieldSpecification__c = '3';
   update poll;
    
    }
    
}