src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountNature__c</fullName>
        <label>客户性质</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
                <value>
                    <fullName>集团客户</fullName>
                </value>
                <value>
                    <fullName>个案代理商</fullName>
                </value>
                <value>
                    <fullName>区域签约代理商</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <label>客户类别</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AccountNature__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>公立综合</fullName>
                </value>
                <value>
                    <fullName>公立眼科专科</fullName>
                </value>
                <value>
                    <fullName>民营综合</fullName>
                </value>
                <value>
                    <fullName>民营眼科专科</fullName>
                </value>
                <value>
                    <fullName>集团综合</fullName>
                </value>
                <value>
                    <fullName>集团眼科专科</fullName>
                </value>
                <value>
                    <fullName>公立其他</fullName>
                </value>
                <value>
                    <fullName>集团其他</fullName>
                </value>
                <value>
                    <fullName>民营其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BigCustomer__c</fullName>
        <inlineHelpText>200万以上的客户是大项目客户。</inlineHelpText>
        <label>大项目客户</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CountyHospital__c</fullName>
        <label>县级医院</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>客户性质等级</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AccountNature__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>公立三级</fullName>
                </value>
                <value>
                    <fullName>公立二级</fullName>
                </value>
                <value>
                    <fullName>公立一级</fullName>
                </value>
                <value>
                    <fullName>爱尔集团</fullName>
                </value>
                <value>
                    <fullName>朝聚集团</fullName>
                </value>
                <value>
                    <fullName>华厦集团</fullName>
                </value>
                <value>
                    <fullName>华正集团</fullName>
                </value>
                <value>
                    <fullName>新视界集团</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
                <value>
                    <fullName>阿玛施集团</fullName>
                </value>
                <value>
                    <fullName>普瑞集团</fullName>
                </value>
                <value>
                    <fullName>无</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NewAccount__c</fullName>
        <label>新建医院</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesActivityDivision__c</fullName>
        <label>销售活动区分</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeEnterprise__c</fullName>
        <label>客户类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>生产单位</fullName>
                </value>
                <value>
                    <fullName>经营单位</fullName>
                </value>
                <value>
                    <fullName>医疗机构</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                    <isActive>false</isActive>
                    <label>其他</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>渝中区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EventOnAccountTest.cls
@isTest(seeAllData=true)
private class EventOnAccountTest {

    @isTest static void test_method_one() {
        Account d = new Account();
        d.Name='a';
        d.province__c='重庆市';
        d.city__c='渝中区';
        d.Cunty__c='111';
        d.NewAccount__c='否';
        d.CountyHospital__c='否';
        d.TypeEnterprise__c='医疗机构';
        d.AccountType__c='综合';
        d.BigCustomer__c='是';
        d.AccountNature__c='公立医院';
        d.Grade__c='公立二级';
        d.SalesActivityDivision__c=null;
        insert d;
        
        Account d2 = new Account();
        d2.Name='b';
        d2.province__c='重庆市';
        d2.city__c='渝中区';
        d2.Cunty__c='111';
        d2.NewAccount__c='否';
        d2.CountyHospital__c='否';
        d2.TypeEnterprise__c='医疗机构';
        d2.AccountType__c='综合';
        d2.BigCustomer__c='是';
        d2.AccountNature__c='公立医院';
        d2.Grade__c='公立二级';
        d2.SalesActivityDivision__c=null;
        insert d2;
        
        Account d3 = new Account();
        d3.Name='c';
        d3.province__c='重庆市';
        d3.city__c='渝中区';
        d3.Cunty__c='111';
        d3.NewAccount__c='否';
        d3.CountyHospital__c='否';
        d3.TypeEnterprise__c='医疗机构';
        d3.AccountType__c='综合';
        d3.BigCustomer__c='是';
        d3.AccountNature__c='公立医院';
        d3.Grade__c='公立二级';
        d3.SalesActivityDivision__c=null;
        insert d3;

        Event s = new Event();
        s.AccountName__c = d.Id;
        s.ActivitiesDistinguish__c='客户相关活动';
        s.DurationInMinutes=10;
        s.ActivityDateTime=DateTime.newInstance(2018, 1, 31, 7, 8, 16);
        insert s;
        s.AccountName__c  = d3.Id;
        update s ; 
        
        
        Event s2 =new Event();
        s2.AccountName__c = d.Id;
        s2.ActivitiesDistinguish__c='客户相关活动';
        s2.DurationInMinutes=10;
        s2.ActivityDateTime=DateTime.newInstance(2018, 1, 31, 7, 8, 16);
        insert s2;
        
        Event s3 =new Event();
        s3.AccountName__c = d.Id;
        s3.ActivitiesDistinguish__c='客户相关活动';
        s3.DurationInMinutes=10;
        s3.ActivityDateTime=DateTime.newInstance(2018, 1, 31, 7, 8, 16);
        insert s3;
        
        
        Account acc = [SELECT Id, SalesActivityDivision__c FROM Account WHERE Id=:d.Id];
        Account acc2 = [SELECT Id, SalesActivityDivision__c FROM Account WHERE Id=:d2.Id];
        Account acc3 = [SELECT Id, SalesActivityDivision__c FROM Account WHERE Id=:acc2.Id];
        List<Event> con =[SELECT AccountName__c FROM Event WHERE AccountName__c=:d.Id];
        List<Event> con2 =[SELECT AccountName__c FROM Event WHERE AccountName__c=:d2.Id];
        List<Event> con3 =[SELECT AccountName__c FROM Event WHERE AccountName__c=''];
        System.debug('SalesActivityDivision__c: '+d.SalesActivityDivision__c);

       
        
        test.startTest();
        update s3 ;
        update acc;
        update con;
        delete s3;
        delete s;
        delete s2;
        undelete s;
        update d2;
        insert con2;
        //update con3;
        update acc3;
        test.stopTest();
       
    }

}