src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>area__c</fullName>
        <label>区域</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>clientlevel__c</fullName>
        <label>客户级别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公司VIP</fullName>
                </value>
                <value>
                    <fullName>部门VIP</fullName>
                </value>
                <value>
                    <fullName>普通客户</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>firstclassify__c</fullName>
        <label>客户一级分类</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>集团民营</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E7XU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>installationdate__c</fullName>
        <label>安装日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ismain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否主设备</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>H1io</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantySatart__c</fullName>
        <inlineHelpText>第一次装机后，根据验收时间自动默认保修开始日期</inlineHelpText>
        <label>设备保修开始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <formula>TEXT(customer__r.area__c)</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>oll6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EBhx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>case状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>未响应</fullName>
                </value>
                <value>
                    <fullName>已响应</fullName>
                    <default>true</default>
                    <label>已响应</label>
                </value>
                <value>
                    <fullName>服务中</fullName>
                </value>
                <value>
                    <fullName>等待备件</fullName>
                </value>
                <value>
                    <fullName>未解决，观察中</fullName>
                </value>
                <value>
                    <fullName>已解决，继续观察</fullName>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
                <value>
                    <fullName>安装调试中</fullName>
                </value>
                <value>
                    <fullName>已安装，未调试</fullName>
                </value>
                <value>
                    <fullName>已安装，等待PMMA测试结果</fullName>
                </value>
                <value>
                    <fullName>已安装，PMMA未通过</fullName>
                </value>
                <value>
                    <fullName>关闭（PMMA通过）</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <recordTypes>
        <fullName>htaz</fullName>
        <active>true</active>
        <description>用于记录合同新机安装类型的服务请求</description>
        <label>合同安装</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/sparepart__c.object
<CustomObject>
    <fields>
        <fullName>WarrantyEnd__c</fullName>
        <formula>Field2__r.warrantyEnd__c</formula>
        <label>保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <formula>servicerequest__r.Equipment__r.areanew__c</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>计划使用时间或要求到货时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>备件申请</relationshipLabel>
        <relationshipName>OPjC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>申请性质</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>保外备件销售</fullName>
                </value>
                <value>
                    <fullName>维修备用</fullName>
                </value>
                <value>
                    <fullName>维修测试</fullName>
                </value>
                <value>
                    <fullName>保内维修更换</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>备件申请</label>
    <nameField>
        <displayFormat>BJSQ-{YYYY}{MM}-{00000000}</displayFormat>
        <label>申请编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>备件申请</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/sparepartdetail__c.object
<CustomObject>
    <fields>
        <fullName>number__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>sparepart__c</fullName>
        <label>备件申请名称</label>
        <referenceTo>sparepart__c</referenceTo>
        <relationshipLabel>备件明细</relationshipLabel>
        <relationshipName>K9cG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>当前发货状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未发货</fullName>
                    <default>true</default>
                    <label>未发货</label>
                </value>
                <value>
                    <fullName>已发货</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>备件明细</label>
    <nameField>
        <displayFormat>SD-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>备件明细</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/stock__c.object
<CustomObject>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品编号</label>
        <referenceTo>product__c</referenceTo>
        <relationshipName>GzBJ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态库</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>新品库</fullName>
                </value>
                <value>
                    <fullName>损耗库</fullName>
                </value>
                <value>
                    <fullName>备用机库</fullName>
                </value>
                <value>
                    <fullName>备用机损耗库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>virtualnum__c</fullName>
        <label>可用库存</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>仓库地点</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京库</fullName>
                </value>
                <value>
                    <fullName>上海库</fullName>
                </value>
                <value>
                    <fullName>广州库</fullName>
                </value>
                <value>
                    <fullName>香港库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>库存明细</label>
    <nameField>
        <label>库存编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>库存明细</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cbl_sparepartdetail_state_Test.cls
/*
*Creat By : Arvin
*Email: arvinxiang@frensworkz.com
*Time : 2015年03月05日
*Describe :  Cbl_sparepartdetail_state 的测试类
*/
@isTest
private class Cbl_sparepartdetail_state_Test {

	//测试新建备件明细
    static testMethod void Test_insertspdetail() {
		product__c pro = new product__c();
        pro.Name='test';
        insert pro;
        
        stock__c st=new stock__c();
        st.name='test001';
        st.state__c='新品库';
        st.warehouse__c='北京';
        st.ProductNumber__c=pro.id;
        st.virtualnum__c=10;
        try{
        	insert st;
        }
        catch(Exception e)
       	{
       		
       	}
        
        
        Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
        //UserRole ur=new UserRole(); 
		//ur.Name='01-总经理'; 
		//insert ur; 
		User u=new User(); 
		u.FirstName='李'; 
		u.LastName='四'; 
		u.Alias='李四'; 
		u.Username='lisi@frensworkz.com'; 
		u.Email='lisi@frensworkz.com'; 
		u.CommunityNickname='lisi'; 
		//u.UserRoleId=ur.Id; 
		u.ProfileId=profile.Id; 
		u.TimeZoneSidKey='Asia/Shanghai'; 
		u.LocaleSidKey='en_AU'; 
		u.EmailEncodingKey='UTF-8'; 
		u.LanguageLocaleKey='en_US'; 
		insert u; 
		Account acc=new Account();
		acc.Name='momo医院';
		acc.firstclassify__c='国有医院';
		acc.area__c='北区';
		acc.secondperson__c=u.Id;
		acc.clientlevel__c='公司VIP';
		insert acc;
		Equipment__c equ=new Equipment__c();
		equ.Name='cesixulihao';
		equ.warrantytype__c='全保';
		equ.customer__c=acc.Id;
		equ.ismain__c=true;
		equ.installationdate__c=Date.newInstance(2014, 4, 5);
		equ.warrantySatart__c=Date.newInstance(2014, 4, 5);
		equ.warrantyEnd__c=Date.newInstance(2015, 1, 5);
		insert equ;
		Contact c=new Contact();
		c.LastName='cesi';
		c.AccountId=acc.Id;
		insert c;
		servicerequest__c ser=new servicerequest__c();
		ser.Name='第一次安装';
		ser.RecordTypeId=listrtp[0].Id;
		ser.requesttime__c=Date.today();
		ser.customer__c=acc.Id;
		ser.person__c=c.Id;
		ser.Equipment__c=equ.Id;
		ser.secondperson__c=u.Id;
		insert ser;
        //备件申请
        sparepart__c sp = new sparepart__c();
        sp.spstate__c='草稿';
        sp.situation__c='保修期';
        sp.requesttime__c=Datetime.now();
        sp.servicerequest__c=ser.Id;
         try
        {
        	insert sp;
        }
        catch(Exception e)
       	{
       		
       	}
        sparepartdetail__c spd = new sparepartdetail__c();
        spd.sparepart__c=sp.Id;
        spd.state__c='已发货';
        spd.partnum__c=st.Id;
        spd.number__c=2;
        try{
        	insert spd;
        }
        catch(Exception e)
       	{
       		
       	}
        
        try{
        	delete spd;
        }
        catch(Exception e)
       	{
       		
       	}
    }
    //测试更改备件明细
    static testMethod void Test_updatespdetail() {
		product__c pro = new product__c();
        pro.Name='test';
        insert pro;
        
        kucun__c kc=new kucun__c();
        insert kc;
        
        stock__c st=new stock__c();
        st.name='test001';
        st.state__c='新品库';
        st.warehouse__c='北京';
        st.ProductNumber__c=pro.id;
        st.virtualnum__c=10;
        st.Field2__c=kc.Id;
        insert st;
        
        Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
        //UserRole ur=new UserRole(); 
		//ur.Name='01-总经理'; 
		//insert ur; 
		User u=new User(); 
		u.FirstName='李'; 
		u.LastName='四'; 
		u.Alias='李四'; 
		u.Username='lisi@frensworkz.com'; 
		u.Email='lisi@frensworkz.com'; 
		u.CommunityNickname='lisi'; 
		//u.UserRoleId=ur.Id; 
		u.ProfileId=profile.Id; 
		u.TimeZoneSidKey='Asia/Shanghai'; 
		u.LocaleSidKey='en_AU'; 
		u.EmailEncodingKey='UTF-8'; 
		u.LanguageLocaleKey='en_US'; 
		insert u; 
		Account acc=new Account();
		acc.Name='momo医院';
		acc.firstclassify__c='国有医院';
		acc.area__c='北区';
		acc.secondperson__c=u.Id;
		acc.clientlevel__c='公司VIP';
		insert acc;
		Equipment__c equ=new Equipment__c();
		equ.Name='cesixulihao';
		equ.warrantytype__c='全保';
		equ.customer__c=acc.Id;
		equ.ismain__c=true;
		equ.installationdate__c=Date.newInstance(2014, 4, 5);
		equ.warrantySatart__c=Date.newInstance(2014, 4, 5);
		equ.warrantyEnd__c=Date.newInstance(2015, 1, 5);
		insert equ;
		Contact c=new Contact();
		c.LastName='cesi';
		c.AccountId=acc.Id;
		insert c;
		servicerequest__c ser=new servicerequest__c();
		ser.Name='第一次安装';
		ser.RecordTypeId=listrtp[0].Id;
		ser.requesttime__c=Date.today();
		ser.customer__c=acc.Id;
		ser.person__c=c.Id;
		ser.Equipment__c=equ.Id;
		ser.secondperson__c=u.Id;
		insert ser;
        //备件申请
        sparepart__c sp = new sparepart__c();
        sp.spstate__c='草稿';
        sp.situation__c='保修期';
        sp.requesttime__c=Datetime.now();
        sp.servicerequest__c=ser.Id;
        sp.state__c='维修测试';
        //try
        //{
        	insert sp;
        //}
        //catch(Exception e)
       	//{
       		
       //	}
       	//备件明细
        sparepartdetail__c spd = new sparepartdetail__c();
        spd.sparepart__c=sp.Id;
        spd.partnum__c=st.Id;
        spd.state__c='未发货';
        spd.number__c=2;
        spd.sparepart__c=sp.Id;
        insert spd;
        spd.number__c=4;
        try{
        	update spd;	
        }catch(Exception e)
       	{
       		
       	}
        spd.state__c='已发货';
        try{
        	update spd;	
        }catch(Exception e)
       	{
       		
       	}
        try{
        	delete spd;	
        }catch(Exception e)
       	{
       		
       	}
        
        
    }
    
}