src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>area__c</fullName>
        <label>区域</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>clientlevel__c</fullName>
        <label>客户级别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公司VIP</fullName>
                </value>
                <value>
                    <fullName>部门VIP</fullName>
                </value>
                <value>
                    <fullName>普通客户</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>firstclassify__c</fullName>
        <label>客户一级分类</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>集团民营</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E7XU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ismain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否主设备</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/installreport__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicereport__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>arrivaldate__c</fullName>
        <label>到达日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>completedate__c</fullName>
        <label>完成日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <formula>servicereport__r.customer__r.Name</formula>
        <label>客户名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endtime__c</fullName>
        <label>具体结束工作时间</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>hometime__c</fullName>
        <label>具体到家时间</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>leavetime__c</fullName>
        <label>出发时间</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>oniz</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>qiangzuidashuchunengliang__c</fullName>
        <label>腔最大输出能量（mj）</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>receptiontime__c</fullName>
        <label>验收时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <formula>servicereport__r.requesttime__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>#服务请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>servicereport__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipName>OPhL</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>starttime__c</fullName>
        <label>具体开始工作时间</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>进行中</fullName>
                    <default>true</default>
                    <label>进行中</label>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>安装确认单</label>
    <nameField>
        <displayFormat>I-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>安装确认单</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>附属设备、欧堡安装确认单</description>
        <label>附属设备、欧堡</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicereport__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicerequest__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <formula>servicerequest__r.customer__r.Name</formula>
        <label>客户名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endtime__c</fullName>
        <label>具体结束工作时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>hometime__c</fullName>
        <label>具体到家时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>leavetime__c</fullName>
        <label>出发时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>技术服务报告 (联系人)</relationshipLabel>
        <relationshipName>onYV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>receptiontime__c</fullName>
        <label>验收时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>技术服务报告</relationshipLabel>
        <relationshipName>OPhB</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>starttime__c</fullName>
        <label>具体开始工作时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未开始</fullName>
                </value>
                <value>
                    <fullName>进行中</fullName>
                    <default>true</default>
                    <label>进行中</label>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>技术服务报告</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>技术服务报告</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <formula>TEXT(customer__r.area__c)</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>oll6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EBhx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>case状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>未响应</fullName>
                </value>
                <value>
                    <fullName>已响应</fullName>
                    <default>true</default>
                    <label>已响应</label>
                </value>
                <value>
                    <fullName>服务中</fullName>
                </value>
                <value>
                    <fullName>等待备件</fullName>
                </value>
                <value>
                    <fullName>未解决，观察中</fullName>
                </value>
                <value>
                    <fullName>已解决，继续观察</fullName>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
                <value>
                    <fullName>安装调试中</fullName>
                </value>
                <value>
                    <fullName>已安装，未调试</fullName>
                </value>
                <value>
                    <fullName>已安装，等待PMMA测试结果</fullName>
                </value>
                <value>
                    <fullName>已安装，PMMA未通过</fullName>
                </value>
                <value>
                    <fullName>关闭（PMMA通过）</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <recordTypes>
        <fullName>htaz</fullName>
        <active>true</active>
        <description>用于记录合同新机安装类型的服务请求</description>
        <label>合同安装</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cbl_SendInstallEmail_Test.cls
/**
*Dis:设备安装报告在关闭时，可以生成打印模板，并自动发送报告附件邮件到第一责任人邮箱中  测试类
     trigger中不能使用Blob b = ref.getContentAsPDF(); 
*Time:2015年3月13日11:07:02
*Author:Somnus Wang
**/
@isTest
private class Cbl_SendInstallEmail_Test {

     static testMethod void testFutureCallSuccess(){
        Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
        UserRole ur=new UserRole(); 
        ur.Name='01-总经理'; 
        insert ur; 
        User u=new User();  
        u.FirstName='李';  
        u.LastName='四'; 
        u.Alias='李四'; 
        u.Username='lisi@frensworkz.com'; 
        u.Email='lisi@frensworkz.com'; 
        u.CommunityNickname='lisi'; 
        u.UserRoleId=ur.Id; 
        u.ProfileId=profile.Id; 
        u.TimeZoneSidKey='Asia/Shanghai'; 
        u.LocaleSidKey='en_AU'; 
        u.EmailEncodingKey='UTF-8'; 
        u.LanguageLocaleKey='en_US'; 
        insert u; 
        Account acc=new Account();
        acc.Name='momo医院';
        acc.firstclassify__c='国有医院';
        acc.area__c='北区';
        acc.secondperson__c=u.Id;
        acc.clientlevel__c='公司VIP';
        insert acc;
        Equipment__c equ=new Equipment__c();
        equ.Name='cesixulihao';
        equ.warrantytype__c='全保';
        equ.customer__c=acc.Id;
        equ.ismain__c=true;
        insert equ;
        Contact c=new Contact();
        c.LastName='cesi';
        c.AccountId=acc.Id;
        insert c;
        servicerequest__c ser=new servicerequest__c();
        ser.Name='第一次安装';
        ser.RecordTypeId=listrtp[0].Id;
        ser.requesttime__c=Date.today();
        ser.customer__c=acc.Id;
        ser.person__c=c.Id;
        ser.Equipment__c=equ.Id;
        ser.secondperson__c=u.Id;
        ser.OwnerId=u.Id;
        insert ser;
        //安装确认单
        installreport__c ins=new installreport__c();
        ins.servicereport__c=ser.Id;
        ins.person__c=c.Id;
        ins.state__c='进行中';
        ins.qiangzuidashuchunengliang__c = 2;
        ins.receptiontime__c=Date.today();
        ins.arrivaldate__c=Date.today();
        ins.completedate__c=Date.today();
        ins.endtime__c=Date.today();  
        ins.hometime__c=Date.today();
        ins.leavetime__c=Date.today();
        ins.starttime__c=Date.today();
        insert ins; 
        ins.receptiontime__c=Date.today().addDays(1);
        update ins;
        SendPDFEmail spdf=new SendPDFEmail();
        spdf.test();
        Cbl_SendInstallEmail csie=new Cbl_SendInstallEmail();
        csie.test();
       // Cbl_SendInstallEmail.sendEmail(ins.Id);
     }
        static testmethod void testMe() {
        Test.setMock(HttpCalloutMock.class, new Stubby());
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://cs6.salesforce.com/services/apexrest/sendPDFEmail');
        req.setMethod('POST');
        Http h = new Http();
        Cbl_CreateInstallPDF.createVF('12345678911111111a',UserInfo.getSessionId());
         }
}