src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>职务</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalRepresentative__c</fullName>
        <label>法定代表人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>福州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CustomObject20__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>UzCL</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionAmount__c</fullName>
        <label>维修收费金额（元）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>单次报价</label>
    <nameField>
        <displayFormat>DCWX-{000000}</displayFormat>
        <label>单次报价编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>单次报价</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentCusOb20TriggerTest.cls
@istest
private  class AttachmentCusOb20TriggerTest {
	@istest
    static void TestAttachmentCusOb20Trigger(){
        Account acc  =  new Account() ; 
        acc.Name = 'kehu';
        acc.city__c = '福州市';
        acc.province__c = '福建省';
        acc.Cunty__c = '1' ;
        acc.LegalRepresentative__c = '1';
        acc.Duty__c = '1' ;
        acc.ContactNumber__c = '123'; 
        acc.Gender__c = '男';
        insert acc ; 
        CustomObject20__c newCus = new CustomObject20__c(TransactionAmount__c = 1, Account__c = acc.id);
        insert newCus;
        
        Attachment newAttachment = new Attachment(body = blob.valueOf('aaaa'), Name = '测试附件', ParentId = newCus.id);
    insert newAttachment;
    }
}