src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>area__c</fullName>
        <label>区域</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>clientlevel__c</fullName>
        <label>客户级别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公司VIP</fullName>
                </value>
                <value>
                    <fullName>部门VIP</fullName>
                </value>
                <value>
                    <fullName>普通客户</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>firstclassify__c</fullName>
        <label>客户一级分类</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>集团民营</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E7XU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ismain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否主设备</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/servicereport__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicerequest__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <formula>servicerequest__r.customer__r.Name</formula>
        <label>客户名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstpressureend__c</fullName>
        <label>最终初级气压（Bar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfmjend__c</fullName>
        <label>最终能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnmend__c</fullName>
        <label>最终能量测试HE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hvvend__c</fullName>
        <label>最终能量测试HV（V）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfmjend__c</fullName>
        <label>最终能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnmend__c</fullName>
        <label>最终能量测试LE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>技术服务报告 (联系人)</relationshipLabel>
        <relationshipName>onYV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>技术服务报告</relationshipLabel>
        <relationshipName>OPhB</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>servicetype__c</fullName>
        <label>服务类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>维修</fullName>
                </value>
                <value>
                    <fullName>巡检</fullName>
                </value>
                <value>
                    <fullName>设备升级</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sparepart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>备件申请</label>
        <referenceTo>sparepart__c</referenceTo>
        <relationshipLabel>技术服务报告</relationshipLabel>
        <relationshipName>sparepartWv1v</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未开始</fullName>
                </value>
                <value>
                    <fullName>进行中</fullName>
                    <default>true</default>
                    <label>进行中</label>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>技术服务报告</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>技术服务报告</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <formula>TEXT(customer__r.area__c)</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>oll6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EBhx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>case状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>未响应</fullName>
                </value>
                <value>
                    <fullName>已响应</fullName>
                    <default>true</default>
                    <label>已响应</label>
                </value>
                <value>
                    <fullName>服务中</fullName>
                </value>
                <value>
                    <fullName>等待备件</fullName>
                </value>
                <value>
                    <fullName>未解决，观察中</fullName>
                </value>
                <value>
                    <fullName>已解决，继续观察</fullName>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
                <value>
                    <fullName>安装调试中</fullName>
                </value>
                <value>
                    <fullName>已安装，未调试</fullName>
                </value>
                <value>
                    <fullName>已安装，等待PMMA测试结果</fullName>
                </value>
                <value>
                    <fullName>已安装，PMMA未通过</fullName>
                </value>
                <value>
                    <fullName>关闭（PMMA通过）</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <recordTypes>
        <fullName>htaz</fullName>
        <active>true</active>
        <description>用于记录合同新机安装类型的服务请求</description>
        <label>合同安装</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/sparepart__c.object
<CustomObject>
    <fields>
        <fullName>area__c</fullName>
        <formula>servicerequest__r.Equipment__r.areanew__c</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>计划使用时间或要求到货时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>备件申请</relationshipLabel>
        <relationshipName>OPjC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>situation__c</fullName>
        <label>保修情况</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>保修期</fullName>
                </value>
                <value>
                    <fullName>收费维修</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>spstate__c</fullName>
        <label>审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>审批中</fullName>
                </value>
                <value>
                    <fullName>审批通过</fullName>
                </value>
                <value>
                    <fullName>审批拒绝</fullName>
                </value>
                <value>
                    <fullName>调回</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>申请性质</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>保外备件销售</fullName>
                </value>
                <value>
                    <fullName>维修备用</fullName>
                </value>
                <value>
                    <fullName>维修测试</fullName>
                </value>
                <value>
                    <fullName>保内维修更换</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>备件申请</label>
    <nameField>
        <displayFormat>BJSQ-{YYYY}{MM}-{00000000}</displayFormat>
        <label>申请编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>备件申请</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cbl_SendServiceReportEmail_Test.cls
/**
*Dis:技术服务报告报告在关闭时，可以生成打印模板，并自动发送报告附件邮件到第一责任人邮箱中  测试类
     trigger中不能使用Blob b = ref.getContentAsPDF(); 
*Time:2015年3月13日12:35:03
*Author:Somnus Wang
**/
@isTest
private class Cbl_SendServiceReportEmail_Test { 

      static testMethod void testFutureCallSuccess(){
          
          
         Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
        UserRole ur=new UserRole(); 
        ur.Name='01-总经理'; 
        insert ur; 
        User u=new User(); 
        u.FirstName='李'; 
        u.LastName='四'; 
        u.Alias='李四'; 
        u.Username='lisi@frensworkz.com'; 
        u.Email='lisi@frensworkz.com'; 
        u.CommunityNickname='lisi'; 
        u.UserRoleId=ur.Id; 
        u.ProfileId=profile.Id; 
        u.TimeZoneSidKey='Asia/Shanghai'; 
        u.LocaleSidKey='en_AU'; 
        u.EmailEncodingKey='UTF-8'; 
        u.LanguageLocaleKey='en_US'; 
        insert u; 
          
          System.runAs(u){
              Account acc=new Account();
        acc.Name='momo医院';
        acc.firstclassify__c='国有医院';
        acc.area__c='北区';
        acc.secondperson__c=u.Id;
        acc.clientlevel__c='公司VIP';
        insert acc;
        Equipment__c equ=new Equipment__c();
        equ.Name='cesixulihao';
        equ.warrantytype__c='全保';
        equ.customer__c=acc.Id;
        equ.ismain__c=true;
        insert equ;
        Contact c=new Contact();
        c.LastName='cesi';
        c.AccountId=acc.Id;
        insert c;
        servicerequest__c ser=new servicerequest__c();
        ser.Name='第一次安装';
        ser.RecordTypeId=listrtp[0].Id;
        ser.requesttime__c=Date.today();
        ser.customer__c=acc.Id;
        ser.person__c=c.Id;
        ser.Equipment__c=equ.Id;
        ser.secondperson__c=u.Id;
        ser.OwnerId=u.Id;
        insert ser;
        //备件申请
        sparepart__c sp = new sparepart__c();
        sp.spstate__c='审批中';
        sp.situation__c='保修期';
        sp.requesttime__c=Datetime.now();
        sp.servicerequest__c=ser.Id;
        sp.state__c='维修测试';
        insert sp;
        //故障
        faultcategory__c fg=new faultcategory__c();
        fg.Name='testgz';
        insert fg;
        //服务技术报告
        servicereport__c serp=new servicereport__c();
        serp.servicerequest__c=ser.Id;
        serp.servicetype__c='维修';
        serp.person__c=c.Id;
        serp.state__c='未开始';
        serp.hfmjend__c=6;
        serp.hfnmend__c=5;
        serp.hvvend__c=4;
        serp.lfmjend__c=5;
        serp.lfnmend__c=5;
        serp.firstpressureend__c=6;
        serp.otherpressureend__c=5;
        serp.lasernumend__c=6;
        serp.nlvsmjend__c=8;
        serp.solution__c='dsfhksjdhfksd';
        serp.receptiontime__c=Date.today();
        serp.reportdate__c=Date.today();
        serp.dotime__c=Date.today();
        serp.completetime__c=Date.today();
        serp.endtime__c=Date.today();  
        serp.hometime__c=Date.today();
        serp.leavetime__c=Date.today();
        serp.starttime__c=Date.today();
        serp.bugtype__c=fg.Id;
        serp.information__c='sdsfsdf';
        serp.sparepart__c= sp.Id;
        insert serp;
        serp.hvvend__c=9;
        update serp;
        Cbl_SendServiceReportEmail cssre=new Cbl_SendServiceReportEmail();
        cssre.test();
        //Cbl_SendServiceReportEmail.sendEmail(serp.Id);
          }
          
        
      }     
      static testmethod void testMe() {
        Test.setMock(HttpCalloutMock.class, new Stubby());
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://cs6.salesforce.com/services/apexrest/sendServiceEmail');
        req.setMethod('POST');
        Http h = new Http();
        Cbl_CreateServiceReportPDF.createVF('12345678911111111a',UserInfo.getSessionId());
         }
    }