src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>准分子</fullName>
                </value>
                <value>
                    <fullName>飞白</fullName>
                </value>
                <value>
                    <fullName>路视</fullName>
                </value>
                <value>
                    <fullName>欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+路视</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CustomObject18__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>销售机会</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>销售机会产品</relationshipLabel>
        <relationshipName>Field1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>型号</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Adi__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HRA</fullName>
                </value>
                <value>
                    <fullName>HRA Multicolor</fullName>
                </value>
                <value>
                    <fullName>Multicolor+FFA</fullName>
                </value>
                <value>
                    <fullName>OCT</fullName>
                </value>
                <value>
                    <fullName>OCT2</fullName>
                </value>
                <value>
                    <fullName>HRA+OCT</fullName>
                </value>
                <value>
                    <fullName>HRA+OCT2</fullName>
                </value>
                <value>
                    <fullName>HRT3</fullName>
                </value>
                <value>
                    <fullName>OCT2 Multicolor</fullName>
                </value>
                <value>
                    <fullName>OCTMulticolor</fullName>
                </value>
                <value>
                    <fullName>UWF</fullName>
                </value>
                <value>
                    <fullName>Vitra532</fullName>
                </value>
                <value>
                    <fullName>Supra 532</fullName>
                </value>
                <value>
                    <fullName>YAG</fullName>
                </value>
                <value>
                    <fullName>SLT</fullName>
                </value>
                <value>
                    <fullName>supra810</fullName>
                </value>
                <value>
                    <fullName>supra577</fullName>
                </value>
                <value>
                    <fullName>VMS</fullName>
                </value>
                <value>
                    <fullName>suprascan577</fullName>
                </value>
                <value>
                    <fullName>5CL+XL532FMW</fullName>
                </value>
                <value>
                    <fullName>Axis Nano</fullName>
                </value>
                <value>
                    <fullName>Compact Touch（A超+B超）</fullName>
                </value>
                <value>
                    <fullName>Aviso(A超+B超)</fullName>
                </value>
                <value>
                    <fullName>Aviso(UBM)</fullName>
                </value>
                <value>
                    <fullName>Aviso一体机(A超+B超+UBM)</fullName>
                </value>
                <value>
                    <fullName>Compact Touch UBM</fullName>
                </value>
                <value>
                    <fullName>Proveo8</fullName>
                </value>
                <value>
                    <fullName>Leica 3D</fullName>
                </value>
                <value>
                    <fullName>M844F40</fullName>
                </value>
                <value>
                    <fullName>M844F20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TOTALAMOUNT__c</fullName>
        <formula>QUANTITY__c * UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>销售机会产品</label>
    <nameField>
        <displayFormat>CP-{00000000}</displayFormat>
        <label>销售机会产品编码</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>销售机会产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>针对正常推进的销售机会说明。</description>
        <label>说明</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <formula>Owner.LfourDepartment__c</formula>
        <label>销售机会所有人四级部门</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>最终用户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>销售机会</relationshipLabel>
        <relationshipName>FinalCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityClosingTime__c</fullName>
        <label>机会关闭时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SalesOpportunityStatus__c</fullName>
        <label>销售机会关闭状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>丢单</fullName>
                </value>
                <value>
                    <fullName>中断</fullName>
                </value>
                <value>
                    <fullName>赢单</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeInstallation__c</fullName>
        <inlineHelpText>例如：全款已付，预计12月19日安装。</inlineHelpText>
        <label>预计装机日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>预计成交总金额（元）</label>
        <summarizedField>CustomObject18__c.TotalMoney__c</summarizedField>
        <summaryFilterItems>
            <field>CustomObject18__c.State__c</field>
            <operation>notEqual</operation>
            <value>丢单, 中断</value>
        </summaryFilterItems>
        <summaryForeignKey>CustomObject18__c.Field1__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>cpzj__c</fullName>
        <label>预计成交总金额（停用）（元）</label>
        <summarizedField>OpportunityLineItem.cpzje__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityCondition__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>最终用户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>签单情况</relationshipLabel>
        <relationshipName>Opportunity_Condition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>预计成交总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BarndAndType__c</fullName>
        <label>品牌/型号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClosedDate__c</fullName>
        <label>预计成交日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InstalledDate__c</fullName>
        <label>预计装机时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityClosingTime__c</fullName>
        <label>机会关闭日期</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <description>唯一值为 ownerId + WeeklyReport Id + Opportunity Id + week Number</description>
        <externalId>true</externalId>
        <label>OpportunityId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OpportunityStageName__c</fullName>
        <label>销售机会阶段</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>销售机会名称</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Condition</relationshipLabel>
        <relationshipName>Opportunity_Condition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesWeeklyReport2__c</fullName>
        <label>销售周报</label>
        <referenceTo>SalesWeeklyReport__c</referenceTo>
        <relationshipLabel>销售周报</relationshipLabel>
        <relationshipName>Opportunity_Condition</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StagetDescription__c</fullName>
        <label>现阶段状态进展说明</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>本周</fullName>
                </value>
                <value>
                    <fullName>下周</fullName>
                </value>
                <value>
                    <fullName>本周新增</fullName>
                </value>
                <value>
                    <fullName>本周变化</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>签单情况</label>
    <nameField>
        <displayFormat>Opp-{0000000}</displayFormat>
        <label>签单情况 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Condition</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SalesWeeklyReport__c.object
<CustomObject>
    <fields>
        <fullName>DifferenceNumberThisWeek__c</fullName>
        <label>本周机会变化总数</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>周报开始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>销售经理</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Weekly_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>销售周报</label>
    <nameField>
        <displayFormat>SR-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>销售周报 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>销售周报</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduleCalcChangedOpp.cls
global class ScheduleCalcChangedOpp implements Database.Batchable<sObject>, Schedulable {
    
    public String qurey;
    public Date startDate;
    public Date endDate;
    
    global void execute(SchedulableContext sc) {
        ScheduleCalcChangedOpp temp = new ScheduleCalcChangedOpp();
        database.executeBatch(temp, 10);
    }
    
    global ScheduleCalcChangedOpp()
    {   
        startDate = SalesWeeklyReporHelper.getStartDateOftheWeek();
        endDate = startDate.addDays(6);
        
        //Integer weekNumberConvertToInteger = Integer.valueof(weekNumber);
        qurey = 'select id, OpportunityId, Opportunity.OwnerId, Opportunity.StageName, Opportunity.SalesOpportunityStatus__c, Opportunity.lastmodifieddate, ' +
        		' Opportunity.FinalCustomer__c, Opportunity.Probability, Opportunity.FinalCustomer__r.Id, Opportunity.Name, Opportunity.CloseDate, ' + 
        		//' Opportunity.cpzj__c, Opportunity.TotalAmount__c, Opportunity.TimeInstallation__c, Opportunity.Description__c  from opportunityhistory where Opportunity.stagename != \'成交阶段\' and Opportunity.CloseDate >= :startDate and Opportunity.CloseDate <= :endDate';
    			' Opportunity.cpzj__c, Opportunity.TotalAmount__c, Opportunity.TimeInstallation__c, Opportunity.Description__c  from OpportunityFieldHistory where createddate >= :startDate and createddate <= :endDate and field = \'StageName\'';
    	system.debug('startDate is ' + startDate);
    	system.debug('endDate is ' + endDate);
    	system.debug('qurey is ' + qurey);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(qurey);
    }
    
    global void execute(Database.BatchableContext BC, List<OpportunityFieldHistory> scope)
    {   
    	String weeknumber = SalesWeeklyReporHelper.getWeekNumber ();
        Set<Id> userIds = new Set<Id>();
        Map<Id, Set<Id>> OwnerId2OppNumber = new Map<Id, Set<Id>>();
        Map<Id, Opportunity> oppId2Opportunities = new Map<Id, Opportunity>();
        Set<Id> opportunityIds = new Set<id>();
        for(OpportunityFieldHistory tempopportunityhistory : scope)
        {   
        	userIds.add(tempopportunityhistory.Opportunity.OwnerId);
        	opportunityIds.add(tempopportunityhistory.OpportunityId);
        	oppId2Opportunities.put(tempopportunityhistory.OpportunityId, tempopportunityhistory.Opportunity);
        	if (OwnerId2OppNumber.containskey(tempopportunityhistory.Opportunity.OwnerId))
        	{ 
        		Set<Id> tempOpportunityIds = OwnerId2OppNumber.get(tempopportunityhistory.Opportunity.OwnerId);
        		tempOpportunityIds.add(tempopportunityhistory.OpportunityId);
        		OwnerId2OppNumber.put(tempopportunityhistory.Opportunity.OwnerId, tempOpportunityIds);
        	}
        	else
        	{
        		OwnerId2OppNumber.put(tempopportunityhistory.Opportunity.OwnerId, new Set<Id>{tempopportunityhistory.OpportunityId});
        		
        	}
        }
        //get brand and type
        Map<Id, String> OppId2BrandTypes = new Map<Id, String>();
        for (CustomObject18__c tempchanceproduct : [select id, Model__c, Field1__c from CustomObject18__c where Field1__c in :opportunityIds])
        {
        	if (OppId2BrandTypes.containskey(tempchanceproduct.Field1__c))
        	{ 
        		String tempBrandType = OppId2BrandTypes.get(tempchanceproduct.Field1__c) + tempchanceproduct.Model__c;
        		OppId2BrandTypes.put(tempchanceproduct.Field1__c, tempBrandType);
        	}
        	else
        	{
        		OppId2BrandTypes.put(tempchanceproduct.Field1__c, tempchanceproduct.Model__c);
        	}
        }
        List<SalesWeeklyReport__c> updateSalesWeeklyReports = new List<SalesWeeklyReport__c>();
        List<OpportunityCondition__c> allOpportunityConditions = new List<OpportunityCondition__c>();
        for(SalesWeeklyReport__c tempSalesWeeklyReport : [select id, Ownerid, user__c from SalesWeeklyReport__c where ownerid in :userIds and StartDate__c >= :startDate and StartDate__c <= :endDate])
        {   
            SalesWeeklyReport__c updateSalesWeeklyReport = new SalesWeeklyReport__c();
            updateSalesWeeklyReport.Id = tempSalesWeeklyReport.id;
            updateSalesWeeklyReport.DifferenceNumberThisWeek__c = (OwnerId2OppNumber.containsKey(tempSalesWeeklyReport.Ownerid) ? OwnerId2OppNumber.get(tempSalesWeeklyReport.Ownerid).size() : 0);
            updateSalesWeeklyReports.add(updateSalesWeeklyReport);
            
            Set<Id> currentOnwerOpportunityIds = OwnerId2OppNumber.get(tempSalesWeeklyReport.Ownerid);
            for (Id tempOpportunityId : currentOnwerOpportunityIds)
            {	
            	Opportunity tempOpportunity = oppId2Opportunities.get(tempOpportunityId);
            	String productType = OppId2BrandTypes.get(tempOpportunity.Id);
		        OpportunityCondition__c newOpportunityCondition = new OpportunityCondition__c();
	            newOpportunityCondition.Type__c = '本周变化';
		        if (String.isNotBlank(newOpportunityCondition.Type__c))
		        {
		            newOpportunityCondition.Opportunity__c = tempOpportunity.Id;           
		            newOpportunityCondition.OpportunityId__c = tempOpportunity.ownerid + '' + tempSalesWeeklyReport.Ownerid + '' +  tempOpportunity.Id + '' + weekNumber + newOpportunityCondition.Type__c;
		            system.debug(' newOpportunityCondition.OpportunityId__c :'+ newOpportunityCondition.OpportunityId__c);
		            newOpportunityCondition.Account__c = tempOpportunity.FinalCustomer__c;
		            newOpportunityCondition.Amount__c = tempOpportunity.TotalAmount__c;
		            newOpportunityCondition.ClosedDate__c = tempOpportunity.CloseDate;
		            newOpportunityCondition.InstalledDate__c = tempOpportunity.TimeInstallation__c;
		            newOpportunityCondition.StagetDescription__c = tempOpportunity.Description__c;
		            newOpportunityCondition.SalesWeeklyReport2__c = tempSalesWeeklyReport.id;
		            newOpportunityCondition.BarndAndType__c = productType;
		            newOpportunityCondition.OpportunityStageName__c = tempOpportunity.StageName ;
		            if(tempOpportunity.SalesOpportunityStatus__c == '赢单'){
		                newOpportunityCondition.OpportunityClosingTime__c = tempOpportunity.lastmodifieddate ;
		            }
		            allOpportunityConditions.add(newOpportunityCondition);      
		        }
            }
        }
        
        if (updateSalesWeeklyReports.size() > 0)
        {
        	update updateSalesWeeklyReports;
        }
		if (allOpportunityConditions.size() > 0)
		{
			upsert allOpportunityConditions;
		}
    }
    
    global void finish(Database.BatchableContext BC){}

    
}