src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>职务</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalRepresentative__c</fullName>
        <label>法定代表人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>福州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConfigurationList__c.object
<CustomObject>
    <fields>
        <fullName>configurationList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>库存名称</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ConfigurationList__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>库存</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ConfigurationList__c</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>configurationList2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>订单</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>order23</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>配置单/报价单</label>
    <nameField>
        <displayFormat>PZD-{YYYYMMDD}-{000000000}</displayFormat>
        <label>配置单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>配置单/报价单</pluralLabel>
    <recordTypes>
        <fullName>ConfigurationList</fullName>
        <active>true</active>
        <label>配置单-大型</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/URLConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>系统集成配置</label>
</CustomObject>

src/classes/OrderHelperTest.cls
/**
* test for OrderHelper
*** */
@isTest
private class OrderHelperTest {
	
	public class MockHttpResponseGenerator implements HttpCalloutMock {
	    // Implement this interface method
	    public HTTPResponse respond(HTTPRequest req) {
	        // Create a fake response
	        HttpResponse res = new HttpResponse();
	        res.setHeader('Content-Type', 'text/xml');
	        res.setBody('<?xml version="1.0" encoding="UTF-8"?>' +
						'<ufinterface billtype="30" filename="30246d797default.xml" isexchange="Y" replace="Y" roottag="sendresult" sender="default" successful="N">' +
						    '<sendresult>' +
						        '<billpk>' +
						        '</billpk>' +
						        '<bdocid>1655246d7bd000000000000000000000000000300</bdocid>' +
						        '<filename>30246d797default.xml</filename>' +
						        '<resultcode>-32000</resultcode>' +
						        '<resultdescription></resultdescription>' +
						        '<content></content>' +
						    '</sendresult>' +
						'</ufinterface>');
	        res.setStatusCode(200);
	        return res;
	    }
	}
	
    static testMethod void myUnitTest() {
		
		URLConfig__c tempURLConfig = new URLConfig__c(Name = 'RequestURL', URL__c = 'https://www.baidu.com');   
		insert tempURLConfig;
        Account acc  =  new Account() ; 
        acc.Name = 'test1230';
        acc.city__c = '福州市';
        acc.province__c = '福建省';
        acc.Cunty__c = '1' ;
        acc.LegalRepresentative__c = '1';
        acc.Duty__c = '1' ;
        acc.ContactNumber__c = '123'; 
        acc.Gender__c = '男';
        insert acc ;
        
        Order or1 = new  Order();
        or1.AccountId = acc.Id ;
        or1.EffectiveDate = date.today();
        or1.Status = 'Draft';
        insert or1;
		
		ConfigurationList__c configurationlist = new ConfigurationList__c();
		//configurationlist.Name = '333';
		configurationlist.CurrencyIsoCode = 'CNY';
		configurationlist.order__c = or1.Id;
	    insert configurationlist;
		
		Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
		
		OrderHelper.syncOrderinfoByTrigger(or1.id);
		Map<String, String> map1 = OrderHelper.PublicPrivate2Code;
		Map<String, String> map2 = Orderhelper.Classify12Code;
		Map<String, String> map3 = Orderhelper.Classify22Code;
		Map<String, String> map4 = Orderhelper.Classify32Code;
		Map<String, String> map5 = Orderhelper.orderTypeName2Code;
		Map<String, String> map6 = Orderhelper.unitTranslation;
		Map<String, String> map7 = Orderhelper.projectName2Code;
		String tempStr = Orderhelper.convertDateTimetoString(datetime.now());
		Decimal tempD = Orderhelper.setCustomScale(1.02222, 2);
		//Map<String, String> map8 = Orderhelper.orderTypeName2Code;
        
    }
}