src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRMCodingFormula__c</fullName>
        <formula>&apos;SF&apos; + (CRMCoding__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>客户编码</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CountyHospital__c</fullName>
        <label>县级医院</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerApprovalStatus__c</fullName>
        <label>客户审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NewAccount__c</fullName>
        <label>新建医院</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TypeEnterprise__c</fullName>
        <label>客户类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>生产单位</fullName>
                </value>
                <value>
                    <fullName>经营单位</fullName>
                </value>
                <value>
                    <fullName>医疗机构</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                    <isActive>false</isActive>
                    <label>其他</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SyncFirstAccountRestServiceTest.cls
/**
 * test for SyncFirstAccountRestService
 */
@isTest
private class SyncFirstAccountRestServiceTest {

    static testMethod void myUnitTest() {
        
        Account newAccount = new Account(Name = '测试客户', NewAccount__c = '否', CountyHospital__c = '否', TypeEnterprise__c = '医疗机构', CustomerApprovalStatus__c = '草稿');
        insert newAccount;
        Account currentAccount = [select CRMCodingFormula__c from account where id = :newAccount.id limit 1];
        String instanceUrl = URL.getSalesforceBaseUrl().toExternalForm();
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        //validate param
        req.requestURI = instanceUrl + '/services/apexrest/SyncFirstAccountRestService';  
        system.debug('instanceUrl info is ' + instanceUrl);
        req.httpMethod = 'POST';
        String requestParam = '<?xml version="1.0" encoding="UTF-8"?>' +
                    '<request>' +
                      '<TheFirstProduct>是</TheFirstProduct>' + 
                      '<FieldVisitQualified>状态良好</FieldVisitQualified>' + 
                      '<CustomerFirst>是</CustomerFirst>' + 
                      '<ProposedSpecies>拟供品种</ProposedSpecies>' + 
                      '<PermitNumber>GB-111111</PermitNumber>' + 
                      '<QualityManager>张经理</QualityManager>' + 
                      '<CRMCoding>' + currentAccount.CRMCodingFormula__c + '</CRMCoding>' + 
                      '<SalesOrganization>高视</SalesOrganization>' +  
                      '<ThroughTheFirstCamp>是</ThroughTheFirstCamp>' +
                    '</request>';
        req.requestBody = Blob.valueof(requestParam);
        RestContext.request = req;
        RestContext.response = res;
        SyncFirstAccountRestService.createFirstAccount();     
        
        RestRequest req1 = new RestRequest(); 
        RestResponse res1 = new RestResponse();
        //validate param
        req1.requestURI = instanceUrl + '/services/apexrest/SyncFirstAccountRestService';  
        system.debug('instanceUrl info is ' + instanceUrl);
        req1.httpMethod = 'POST';
        String requestParam1 = '<?xml version="1.0" encoding="UTF-8"?>' +
                    '<request>' +
                      ' <TheFirstProduct>是</TheFirstProduct>' + 
                      ' <FieldVisitQualified>状态良好</FieldVisitQualified>' + 
                      ' <CustomerFirst>是</CustomerFirst>' + 
                      ' <ProposedSpecies>拟供品种</ProposedSpecies>' + 
                      ' <PermitNumber>GB-111111</PermitNumber>' + 
                      ' <QualityManager>张经理</QualityManager>' + 
                      ' <CRMCoding>' + currentAccount.CRMCodingFormula__c + '</CRMCoding>' + 
                      ' <SalesOrganization>高视</SalesOrganization>' + 
                      ' <ThroughTheFirstCamp>是</ThroughTheFirstCamp>' + 
                    '</request>';
        req1.requestBody = Blob.valueof(requestParam1);
        RestContext.request = req1;
        RestContext.response = res1;
        SyncFirstAccountRestService.createFirstAccount();    
    }
}