src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <label>联系电话</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Cunty__c</fullName>
        <inlineHelpText>例如：北京市延庆县，此字段填：延庆县</inlineHelpText>
        <label>县/县级市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty__c</fullName>
        <label>职务</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性别</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>男</fullName>
                </value>
                <value>
                    <fullName>女</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LegalRepresentative__c</fullName>
        <label>法定代表人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>city__c</fullName>
        <label>市/区</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>province__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>东城区</fullName>
                </value>
                <value>
                    <fullName>西城区</fullName>
                </value>
                <value>
                    <fullName>朝阳区</fullName>
                </value>
                <value>
                    <fullName>丰台区</fullName>
                </value>
                <value>
                    <fullName>石景山区</fullName>
                </value>
                <value>
                    <fullName>海淀区</fullName>
                </value>
                <value>
                    <fullName>门头沟区</fullName>
                </value>
                <value>
                    <fullName>房山区</fullName>
                </value>
                <value>
                    <fullName>通州区</fullName>
                </value>
                <value>
                    <fullName>顺义区</fullName>
                </value>
                <value>
                    <fullName>昌平区</fullName>
                </value>
                <value>
                    <fullName>大兴区</fullName>
                </value>
                <value>
                    <fullName>怀柔区</fullName>
                </value>
                <value>
                    <fullName>平谷区</fullName>
                </value>
                <value>
                    <fullName>密云县</fullName>
                </value>
                <value>
                    <fullName>延庆县</fullName>
                </value>
                <value>
                    <fullName>和平区</fullName>
                </value>
                <value>
                    <fullName>河东区</fullName>
                </value>
                <value>
                    <fullName>河西区</fullName>
                </value>
                <value>
                    <fullName>南开区</fullName>
                </value>
                <value>
                    <fullName>河北区</fullName>
                </value>
                <value>
                    <fullName>红桥区</fullName>
                </value>
                <value>
                    <fullName>塘沽区</fullName>
                </value>
                <value>
                    <fullName>汉沽区</fullName>
                </value>
                <value>
                    <fullName>大港区</fullName>
                </value>
                <value>
                    <fullName>东丽区</fullName>
                </value>
                <value>
                    <fullName>西青区</fullName>
                </value>
                <value>
                    <fullName>津南区</fullName>
                </value>
                <value>
                    <fullName>北辰区</fullName>
                </value>
                <value>
                    <fullName>武清区</fullName>
                </value>
                <value>
                    <fullName>福州市</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>province__c</fullName>
        <label>省/直辖市</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京市</fullName>
                </value>
                <value>
                    <fullName>天津市</fullName>
                </value>
                <value>
                    <fullName>上海市</fullName>
                </value>
                <value>
                    <fullName>重庆市</fullName>
                </value>
                <value>
                    <fullName>河北省</fullName>
                </value>
                <value>
                    <fullName>山西省</fullName>
                </value>
                <value>
                    <fullName>辽宁省</fullName>
                </value>
                <value>
                    <fullName>吉林省</fullName>
                </value>
                <value>
                    <fullName>黑龙江省</fullName>
                </value>
                <value>
                    <fullName>江苏省</fullName>
                </value>
                <value>
                    <fullName>浙江省</fullName>
                </value>
                <value>
                    <fullName>安徽省</fullName>
                </value>
                <value>
                    <fullName>福建省</fullName>
                </value>
                <value>
                    <fullName>江西省</fullName>
                </value>
                <value>
                    <fullName>山东省</fullName>
                </value>
                <value>
                    <fullName>河南省</fullName>
                </value>
                <value>
                    <fullName>湖北省</fullName>
                </value>
                <value>
                    <fullName>湖南省</fullName>
                </value>
                <value>
                    <fullName>广东省</fullName>
                </value>
                <value>
                    <fullName>海南省</fullName>
                </value>
                <value>
                    <fullName>四川省</fullName>
                </value>
                <value>
                    <fullName>贵州省</fullName>
                </value>
                <value>
                    <fullName>云南省</fullName>
                </value>
                <value>
                    <fullName>陕西省</fullName>
                </value>
                <value>
                    <fullName>甘肃省</fullName>
                </value>
                <value>
                    <fullName>青海省</fullName>
                </value>
                <value>
                    <fullName>台湾省</fullName>
                </value>
                <value>
                    <fullName>宁夏回族自治区</fullName>
                </value>
                <value>
                    <fullName>新疆维吾尔自治区</fullName>
                </value>
                <value>
                    <fullName>香港特别行政区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ConfigurationList__c.object
<CustomObject>
    <fields>
        <fullName>configurationList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>库存名称</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ConfigurationList__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>库存</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ConfigurationList__c</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>configurationList2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cpx__c</fullName>
        <label>产品线</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>海德堡</fullName>
                </value>
                <value>
                    <fullName>光太激光</fullName>
                </value>
                <value>
                    <fullName>光太超声</fullName>
                </value>
                <value>
                    <fullName>徕卡</fullName>
                </value>
                <value>
                    <fullName>歌德</fullName>
                </value>
                <value>
                    <fullName>罗兰</fullName>
                </value>
                <value>
                    <fullName>KOWA</fullName>
                </value>
                <value>
                    <fullName>NeoMedix</fullName>
                </value>
                <value>
                    <fullName>Frastema</fullName>
                </value>
                <value>
                    <fullName>OPTOS</fullName>
                </value>
                <value>
                    <fullName>SCHWIND</fullName>
                </value>
                <value>
                    <fullName>LENSAR</fullName>
                </value>
                <value>
                    <fullName>LUNEAU</fullName>
                </value>
                <value>
                    <fullName>HAI</fullName>
                </value>
                <value>
                    <fullName>HEINE</fullName>
                </value>
                <value>
                    <fullName>TOKA</fullName>
                </value>
                <value>
                    <fullName>GI</fullName>
                </value>
                <value>
                    <fullName>Espansione</fullName>
                </value>
                <value>
                    <fullName>Diopsys</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Vrmagic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>配置单/报价单</label>
    <nameField>
        <displayFormat>PZD-{YYYYMMDD}-{000000000}</displayFormat>
        <label>配置单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>配置单/报价单</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessOpportunityApprovalStatus__c</fullName>
        <label>销售机会审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessSource__c</fullName>
        <label>商机来源</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>专家推荐</fullName>
                </value>
                <value>
                    <fullName>学术会议</fullName>
                </value>
                <value>
                    <fullName>主动拜访</fullName>
                </value>
                <value>
                    <fullName>渠道</fullName>
                </value>
                <value>
                    <fullName>内部交流</fullName>
                </value>
                <value>
                    <fullName>网路信息</fullName>
                </value>
                <value>
                    <fullName>同行交流</fullName>
                </value>
                <value>
                    <fullName>竞品预警</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                    <label>线索池</label>
                </value>
                <value>
                    <fullName>客户资产</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessType__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>是否是大项目</inlineHelpText>
        <label>商机类型</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>市/区</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinalCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>最终用户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>销售机会</relationshipLabel>
        <relationshipName>FinalCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcurementMethod__c</fullName>
        <label>采购方式</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>院内采购</fullName>
                </value>
                <value>
                    <fullName>招投标</fullName>
                </value>
                <value>
                    <fullName>融资租赁</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Province__c</fullName>
        <label>省/直辖市</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeInstallation__c</fullName>
        <inlineHelpText>例如：全款已付，预计12月19日安装。</inlineHelpText>
        <label>预计装机日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>jdxspzt__c</fullName>
        <label>阶段性审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ProductLineTest.cls
@isTest
public class ProductLineTest {
	@istest(SeeAlldata=true)
    static void test () {
        
     Account acc  =  new Account() ; 
     acc.Name = 'kehu';
     acc.city__c = '福州市';
     acc.province__c = '福建省';
     acc.Cunty__c = '1' ;
     acc.LegalRepresentative__c = '1';
     acc.Duty__c = '1' ;
     acc.ContactNumber__c = '123'; 
     acc.Gender__c = '男';
     insert acc ;
     
     Opportunity opp = new Opportunity();
	 opp.Name = '11222';
	 opp.StageName = '潜在阶段';
	 opp.Amount = 0.0;
	 opp.Probability = 10.0;
	 opp.CloseDate = Date.newInstance(2018,08,13);
	 opp.CurrencyIsoCode = 'CNY';
	 opp.ProcurementMethod__c = '院内采购';
	 opp.BusinessSource__c = '专家推荐';
	 opp.BusinessType__c = false;
	 opp.FinalCustomer__c = acc.id;
	 opp.BusinessOpportunityApprovalStatus__c = '草稿';
	 opp.jdxspzt__c = '草稿';
	 opp.TimeInstallation__c = Date.newInstance(2018,08,13);
     insert opp;
     
     ConfigurationList__c con1 = new ConfigurationList__c();
	 //con1.Name = '海德堡HRA';
     con1.RecordTypeId='0126F000001UVaSQAW';
	 con1.CurrencyIsoCode = 'CNY';
	 con1.cpx__c = '海德堡';
	 con1.xh__c = 'HRA';
     insert con1;
        
     ConfigurationList__c con = new ConfigurationList__c();
	 //con.Name = '111 HRA 2018-8-13';
	 con.ConfigName__c ='111 HRA 2018-8-13';
	 con.CurrencyIsoCode = 'CNY';
	 con.Opportuniy__c = opp.Id;
	 con.cpx__c = '海德堡';
	 con.xh__c = 'HRA';
     insert con;
     
     
    
    }
    
}