src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>准分子</fullName>
                </value>
                <value>
                    <fullName>飞白</fullName>
                </value>
                <value>
                    <fullName>路视</fullName>
                </value>
                <value>
                    <fullName>欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+路视</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <label>区域</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>clientlevel__c</fullName>
        <label>客户级别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公司VIP</fullName>
                </value>
                <value>
                    <fullName>部门VIP</fullName>
                </value>
                <value>
                    <fullName>普通客户</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>firstclassify__c</fullName>
        <label>客户一级分类</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>公立医院</fullName>
                </value>
                <value>
                    <fullName>集团民营</fullName>
                </value>
                <value>
                    <fullName>单体民营</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>E7XU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/chance__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>保修项目报价</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>保修设备</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMARIS 1050RS</fullName>
                </value>
                <value>
                    <fullName>AMARIS</fullName>
                </value>
                <value>
                    <fullName>AMARIS 500E/Compact</fullName>
                </value>
                <value>
                    <fullName>P200</fullName>
                </value>
                <value>
                    <fullName>200TX</fullName>
                </value>
                <value>
                    <fullName>Daytona</fullName>
                </value>
                <value>
                    <fullName>VX120</fullName>
                </value>
                <value>
                    <fullName>Keratron/Keratron Scout</fullName>
                </value>
                <value>
                    <fullName>Combi</fullName>
                </value>
                <value>
                    <fullName>Irx3</fullName>
                </value>
                <value>
                    <fullName>Sirius</fullName>
                </value>
                <value>
                    <fullName>AMARIS 750S</fullName>
                </value>
                <value>
                    <fullName>ESIRIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <formula>TEXT(customer__r.area__c)</formula>
        <label>区域</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>医院</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IDS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expireX1__c</fullName>
        <label>设备过保日期</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>possible__c</fullName>
        <label>可能性</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                </value>
                <value>
                    <fullName>0%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>阶段</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未启动</fullName>
                </value>
                <value>
                    <fullName>项目启动</fullName>
                    <default>true</default>
                    <label>项目启动</label>
                </value>
                <value>
                    <fullName>项目推进</fullName>
                </value>
                <value>
                    <fullName>项目谈判</fullName>
                </value>
                <value>
                    <fullName>合同签订中</fullName>
                </value>
                <value>
                    <fullName>已签合同</fullName>
                </value>
                <value>
                    <fullName>失去</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>推荐保修模式</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3年全保</fullName>
                    <default>true</default>
                    <label>3年全保</label>
                </value>
                <value>
                    <fullName>技术保修</fullName>
                </value>
                <value>
                    <fullName>1年全保</fullName>
                </value>
                <value>
                    <fullName>5年全保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>业务机会（技术用）</label>
    <nameField>
        <label>业务机会名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>业务机会（技术用）</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Warranty__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>保修年限</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>area__c</fullName>
        <label>#区域#old</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北区</fullName>
                </value>
                <value>
                    <fullName>东区</fullName>
                </value>
                <value>
                    <fullName>南区</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>chance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>业务机会</label>
        <referenceTo>chance__c</referenceTo>
        <relationshipLabel>保修合约</relationshipLabel>
        <relationshipName>AhSl</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>保修合约</relationshipLabel>
        <relationshipName>Fns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>prince__c</fullName>
        <label>保修总价</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>serviceperiod__c</fullName>
        <label>保修年限（隐藏）</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>全保</fullName>
                </value>
                <value>
                    <fullName>技术保修</fullName>
                </value>
                <value>
                    <fullName>单次付费</fullName>
                </value>
                <value>
                    <fullName>半保-不含激光腔</fullName>
                </value>
                <value>
                    <fullName>Credit code服务费</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>保修合约</label>
    <nameField>
        <label>合约名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>保修合约</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cbl_Warranty_updateChance_Test.cls
/**
 * Creat By : Jmark
 * Time : 2016年9月14日10:05:15
 * Describe: 【业务机会】中的最终成交价=【保修合约】的保修价格。   
*/
@isTest
private class Cbl_Warranty_updateChance_Test {

    static testMethod void myUnitTest() {
        Profile profile=[Select p.Name, p.Id From Profile p where Name='系统管理员']; 
        list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
        UserRole ur=new UserRole(); 
		ur.Name='01-总经理'; 
		insert ur; 
		User u=new User(); 
		u.FirstName='李'; 
		u.LastName='四'; 
		u.Alias='李四'; 
		u.Username='lisi@frensworkz.com'; 
		u.Email='lisi@frensworkz.com'; 
		u.CommunityNickname='lisi'; 
		u.UserRoleId=ur.Id; 
		u.ProfileId=profile.Id; 
		u.TimeZoneSidKey='Asia/Shanghai'; 
		u.LocaleSidKey='en_AU'; 
		u.EmailEncodingKey='UTF-8'; 
		u.LanguageLocaleKey='en_US'; 
		insert u; 
		Account acc=new Account();
		acc.Name='momo医院';
		acc.firstclassify__c='国有医院';
		acc.area__c='北区';
		acc.secondperson__c=u.Id;
		acc.clientlevel__c='公司VIP';
		insert acc;
		Contact c=new Contact();
        c.LastName='cesi';
        c.AccountId=acc.Id;
        insert c;
		chance__c cha = new chance__c();
        cha.Name = 'testchance';
        cha.customer__c = acc.Id;
        cha.stage__c = '已回款';
        cha.possible__c = '100%';
        cha.X1__c = 'AMARIS 500E/Compact';
        cha.expireX1__c = Date.today().addYears(1);
        cha.type__c = '1年全保';
        cha.Field1__c = 320000;
        insert cha;
        Warranty__c wty=new Warranty__c();
		wty.Name='测试保修合约';
		wty.warrantytype__c='全保';
		wty.serviceperiod__c='3年';
		wty.customer__c=acc.Id;
		wty.area__c='北区';
		wty.chance__c = cha.Id;
		wty.prince__c = 1000;
		insert wty;
		delete wty;
    }
}