src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerFirst__c</fullName>
        <label>客户是否首营</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                    <default>true</default>
                    <label>否</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>准分子</fullName>
                </value>
                <value>
                    <fullName>飞白</fullName>
                </value>
                <value>
                    <fullName>路视</fullName>
                </value>
                <value>
                    <fullName>欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+欧堡</fullName>
                </value>
                <value>
                    <fullName>准分子+路视</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractReviewStatus__c</fullName>
        <label>合同评审状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否上传附件</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>customerfirst__c</fullName>
        <formula>text(Account.CustomerFirst__c)</formula>
        <label>客户是否首营</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContractAfterTriggerTest.cls
/**
 */
@isTest
private class ContractAfterTriggerTest {

    static testMethod void myUnitTest() {
		
		Account newAccount = new Account (Name = '测试最终客户', CustomerFirst__c = '是');
		insert newAccount;
		Contract newContract = new Contract(accountid = newAccount.Id, ContractReviewStatus__c = '草稿', Field1__c = true, StartDate = date.today());
		insert newContract;
		newContract.ContractReviewStatus__c = '已审批';
		update newContract;
    }
}