src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRMCodingFormula__c</fullName>
        <formula>&apos;SF&apos; + (CRMCoding__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>客户编码</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerFirst__c</fullName>
        <label>客户是否首营</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                    <default>true</default>
                    <label>否</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FieldVisitQualified__c</fullName>
        <label>实地考察合格</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermitNumber__c</fullName>
        <label>许可证号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLine__c</fullName>
        <label>产品线</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProposedSpecies__c</fullName>
        <label>拟供品种</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QualityManager__c</fullName>
        <label>质量负责人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TheFirstProduct__c</fullName>
        <label>产品是否首营</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CustomerFirstManagement__c.object
<CustomObject>
    <fields>
        <fullName>CustomerCode__c</fullName>
        <label>客户编码</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerFirst__c</fullName>
        <label>客户是否首营</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FieldVisitQualified__c</fullName>
        <label>实地考察合格</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>客户首营信息</relationshipLabel>
        <relationshipName>Name</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PermitNumber__c</fullName>
        <label>许可证号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProposedSpecies__c</fullName>
        <label>拟供品种</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QualityManager__c</fullName>
        <label>质量负责人</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesOrganization__c</fullName>
        <label>销售组织</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TheFirstProduct__c</fullName>
        <label>产品是否首营</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThroughTheFirstCamp__c</fullName>
        <label>是否通过首营</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>是</fullName>
                </value>
                <value>
                    <fullName>否</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>客户首营信息</label>
    <nameField>
        <displayFormat>FA-{000000000}</displayFormat>
        <label>客户首营流水号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>客户首营信息</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DeliveryInformation__c.object
<CustomObject>
    <fields>
        <fullName>ProductName__c</fullName>
        <label>产品名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <label>产品编号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipableQuantity__c</fullName>
        <label>未发货数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShippedQuantity__c</fullName>
        <label>已发货数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>order1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>订单</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>发货信息</relationshipLabel>
        <relationshipName>order1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>发货信息</label>
    <nameField>
        <label>发货信息 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>发货信息</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product3__c.object
<CustomObject>
    <description>用于产品配置单</description>
    <fields>
        <fullName>Describe__c</fullName>
        <label>描述</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InventoryCommonName__c</fullName>
        <label>存货通用名称</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialClassification__c</fullName>
        <label>物料分类</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaterialCoding__c</fullName>
        <label>物料编码</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>型号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewInventoryCoding__c</fullName>
        <label>新存货编码</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpenQuotationUnitPrice__c</fullName>
        <label>公开报价单价</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OriginalInventoryCoding__c</fullName>
        <label>原存货编码</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryUnit__c</fullName>
        <label>主计量单位</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLine__c</fullName>
        <label>产品线</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistrationNumber__c</fullName>
        <label>注册证号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipableQuantity__c</fullName>
        <label>可发货数量</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaxRate__c</fullName>
        <label>税率</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TotalPrice0fOpenQuotation__c</fullName>
        <label>公开报价总价</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>类型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>主机</fullName>
                </value>
                <value>
                    <fullName>必选配件</fullName>
                </value>
                <value>
                    <fullName>可选配件</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>产品（配置单产品）</label>
    <nameField>
        <label>物料名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品（配置单产品）</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ReturnDetails__c.object
<CustomObject>
    <fields>
        <fullName>ORDER__c</fullName>
        <label>订单</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>回款明细</relationshipLabel>
        <relationshipName>ORDER12</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RemittanceDate__c</fullName>
        <label>回款日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RepaymentAmount__c</fullName>
        <label>回款金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>回款明细</label>
    <nameField>
        <label>回款明细名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>回款明细</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RestServiceCoreLogic.cls
public class RestServiceCoreLogic {
    
    
    public static RestServiceUtil.Result createFirstAccount(RestServiceUtil.FirstAccountRequestParam firstAccountRequestParam)
    {
        RestServiceUtil.Result result = new RestServiceUtil.Result();
        Account tempAccount = new Account();
        try
        {
	        tempAccount = [select id, name, CRMCodingFormula__c from account where CRMCodingFormula__c = :firstAccountRequestParam.CRMCoding limit 1];
        }
        catch(exception e)
        {
        	result.success = false;
            result.message = '客户编码无效。';
            return result;
        }
        CustomerFirstManagement__c newCustomerFirstManagement = new CustomerFirstManagement__c();
        newCustomerFirstManagement.Name__c = tempAccount.Id;
        newCustomerFirstManagement.TheFirstProduct__c = firstAccountRequestParam.TheFirstProduct;
        newCustomerFirstManagement.FieldVisitQualified__c = firstAccountRequestParam.FieldVisitQualified;
        newCustomerFirstManagement.CustomerFirst__c = firstAccountRequestParam.CustomerFirst;
        newCustomerFirstManagement.ProposedSpecies__c = firstAccountRequestParam.ProposedSpecies;
        newCustomerFirstManagement.PermitNumber__c = firstAccountRequestParam.PermitNumber;
        newCustomerFirstManagement.QualityManager__c = firstAccountRequestParam.QualityManager;
        newCustomerFirstManagement.SalesOrganization__c = firstAccountRequestParam.SalesOrganization;
        newCustomerFirstManagement.ThroughTheFirstCamp__c = firstAccountRequestParam.ThroughTheFirstCamp;
        newCustomerFirstManagement.CustomerCode__c = firstAccountRequestParam.CRMCoding;
        
        
        try
        {
            insert newCustomerFirstManagement;
            result.success = true;
            result.message = '首营信息创建成功。';
        }
        catch(Exception e)
        {
            result.success = false;
            result.message = '创建首营客户信息失败：' + e;
        }
        
        return result;
    }
    
    public static RestServiceUtil.Result createProduct(RestServiceUtil.ProductRequestParam productRequestParam)
    {
        RestServiceUtil.Result result = new RestServiceUtil.Result();
        
        
        Product3__c newProduct = new Product3__c();
        newProduct.OpenQuotationUnitPrice__c = productRequestParam.OpenQuotationUnitPrice;
        newProduct.TotalPrice0fOpenQuotation__c = productRequestParam.TotalPrice0fOpenQuotation;
        newProduct.OriginalInventoryCoding__c = productRequestParam.OriginalInventoryCoding;
        newProduct.Model__c = productRequestParam.Model;
        newProduct.Describe__c = productRequestParam.Describe;
        newProduct.Number__c = productRequestParam.NumberString;
        newProduct.NewInventoryCoding__c = productRequestParam.NewInventoryCoding;
        newProduct.Type__c = productRequestParam.Type;
        
        newProduct.TaxRate__c = productRequestParam.TaxRate;
        newProduct.Name = RestServiceUtil.replaceSpcialChart(productRequestParam.Name, '&amp;', '&');
        newProduct.MaterialCoding__c = productRequestParam.MaterialCoding;
        newProduct.MaterialClassification__c = productRequestParam.MaterialClassification;
        newProduct.PrimaryUnit__c = productRequestParam.PrimaryUnit;
        newProduct.ProductLine__c = productRequestParam.ProductLine;
        newProduct.InventoryCommonName__c = RestServiceUtil.replaceSpcialChart(productRequestParam.InventoryCommonName, '&amp;', '&');
        newProduct.RegistrationNumber__c = productRequestParam.RegistrationNumber;
        try
        {   
            List<Product3__c> exsitProducts = [select id from Product3__c where MaterialCoding__c = :productRequestParam.MaterialCoding];
            Product3__c exsitProduct;
            if (exsitProducts.size() > 0)
            {
                exsitProduct = exsitProducts.get(0);
                newProduct.id = exsitProduct.Id;
                update newProduct;
            }
            else
            {
                insert newProduct;
            
            }
            result.success = true;
            result.message = '产品信息创建成功。';
        }
        catch(Exception e)
        {
            result.success = false;
            result.message = '创建产品信息失败：' + e;
        }
        
        return result;
    }
    
    /*
    *发货
    */
    public static RestServiceUtil.Result createOrUpdateDeliveryInfo(RestServiceUtil.DeliveryInfoRequestParam deliveryRequestParam)
    {
        RestServiceUtil.Result result = new RestServiceUtil.Result();
        
        DeliveryInformation__c tempDeliveryInformation = new DeliveryInformation__c();
        tempDeliveryInformation.ProductNumber__c = deliveryRequestParam.ProductNumber;
        tempDeliveryInformation.ShipableQuantity__c = deliveryRequestParam.ShipableQuantity;
        tempDeliveryInformation.ShippedQuantity__c = deliveryRequestParam.ShippedQuantity;
        tempDeliveryInformation.ProductName__c = deliveryRequestParam.ProductName;
        // get order id according to order number.
        try
        {   
            Order currentOrder = null;
            currentOrder = [select id from order where OrderNumber = :deliveryRequestParam.OrderNumber];
            tempDeliveryInformation.order1__c = currentOrder.Id;
        }
        catch(exception e)
        {
            result.success = false;
            result.message = '该订单号码不存在：' + e;
            return result;
        }
        
        try
        {
            insert tempDeliveryInformation;
            result.success = true;
            result.message = '发货信息更新或者创建成功。';
        }
        catch(Exception e)
        {
            result.success = false;
            result.message = '发货信息创建失败：' + e;
        }
        
        return result;
    }
    
    /*
    *回款
    */
    public static RestServiceUtil.Result createOrUpdatePaybackInfo(RestServiceUtil.PayBackinfoRequestParam payBackRequestParam)
    {
        RestServiceUtil.Result result = new RestServiceUtil.Result();
        
        ReturnDetails__c tempReturnDetails = new ReturnDetails__c();
        tempReturnDetails.RepaymentAmount__c = payBackRequestParam.RepaymentAmount;
        try
        {
	        tempReturnDetails.RemittanceDate__c = payBackRequestParam.RemittanceDate;
        }
        catch(Exception e)
        {
        	result.success = false;
            result.message = '时间格式不正确，请修复：' + e;
            return result;
        }
        
        // get order id according to order number.
        try
        {   
            Order currentOrder = null;
            currentOrder = [select id from order where OrderNumber = :payBackRequestParam.OrderNumber];
            tempReturnDetails.Order__c = currentOrder.Id;
        }
        catch(exception e)
        {
            result.success = false;
            result.message = '该订单号码不存在：' + e;
            return result;
        }
        
        
        try
        {
            insert tempReturnDetails;
            result.success = true;
            result.message = '回款信息创建成功。';
        }
        catch(Exception e)
        {
            result.success = false;
            result.message = '回款信息更创建失败：' + e;
        }
        
        return result;
    }
    public static Date formateDateString (String stringDate, String splitChart)
	{   
	    List<String> dateString = stringDate.split(splitChart);
	    Date result = date.today();
	    result = Date.newinstance(Integer.valueOf(dateString[0]), Integer.valueOf(dateString[1]), Integer.valueOf(dateString[2]));
	    return result;
	}
	//2018-08-28 17:38:15
	public static Datetime formateDateTimeString (String stringDateTime, String splitDateChart)
	{   
	    List<String> splitString = stringDateTime.split(' ');
		Datetime result = datetime.now();
		List<String> dateString = splitString[0].split(splitDateChart);
		List<String> timeString = splitString[1].split(':');
		result = DateTime.newinstance(Integer.valueOf(dateString[0]), Integer.valueOf(dateString[1]), Integer.valueOf(dateString[2]), 
									  Integer.valueOf(timeString[0]), Integer.valueOf(timeString[1]), Integer.valueOf(timeString[2]));
	    return result;
	}
    
}