src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Equipment__c.customer__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求（常规）</relationshipLabel>
        <relationshipName>Equipment1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YES7__c</fullName>
        <defaultValue>false</defaultValue>
        <description>详细解读并签收产品的培训流程</description>
        <label>是</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>工程师</label>
        <referenceTo>User</referenceTo>
        <relationshipName>engineer11</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>工程师</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Engineer112</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceCreatedDateTriggerTest.cls
@isTest
private class ServiceCreatedDateTriggerTest 
{

    @istest(SeeAlldata=true)
    static void testServiceCreatedDateTrigger()
    {  
        Account acc =  new Account();
        acc.Name = 'Test9999';
        insert acc;
        Contact  con  =  new Contact();
        con.LastName = 'T1';
        con.AccountId = acc.Id;
        insert con;
        Equipment__c  eq =  new Equipment__c();
        eq.customer__c = acc.Id ; 
        eq.Name  = '12';
        insert eq;
        
       Id orderTypeIdA = Schema.SObjectType.Case.getRecordTypeInfosByName().get('合同安装').getRecordTypeId();
       Case newCa = new Case(); 
       newCa.RecordTypeId = orderTypeIdA  ; 
       //newCa.engineer__c = u.Id;
       newCa.Origin = '自建';
       newCa.Equipment__c = eq.Id ;
       newCa.ContactId = con.Id ;
       newCa.AccountId = acc.Id ;
       newCa.YES7__c  = true ;
       insert newCa ; 
       
       WorkType wt = new WorkType();
       wt.Name = '123';
       wt.EstimatedDuration = 12.00;
       wt.ShouldAutoCreateSvcAppt = true ;
       insert wt ;
       
       WorkOrder wo = new WorkOrder();
       wo.WorkTypeId = wt.Id ;
       wo.CaseId = newCa.Id ;
       insert wo ;
       
       
       
    }
}