src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CompleteTime__c</fullName>
        <label>完成时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReturnTime__c</fullName>
        <label>回访时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VerySatisfied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>非常满意</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WorkDate__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>upgrade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否升级</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CompleteTimeTest.cls
@isTest
private class  CompleteTimeTest 
{

    @istest(SeeAlldata=true)
    static void testCompleteTimeTrigger ()
    {
  Case case1 = new Case(
    RecordTypeId = '0126F00000175p4QAA',
    Status = '等待备件',
    Origin = 'Call Center',
    Priority = 'Medium',
    IsEscalated = false,
    CurrencyIsoCode = 'CNY',
    OwnerId = '0056F0000082F6LQAU',
    WorkDate__c = Date.newInstance(2018,06,24),
    VerySatisfied__c = false,
    ReturnTime__c = Date.newInstance(2018,06,25),
    upgrade__c = false,
    CompleteTime__c = Date.newInstance(2018,06,25));
     insert case1 ;


}
}