src/objects/chance__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>保修项目报价</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1__c</fullName>
        <label>保修设备</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AMARIS 1050RS</fullName>
                </value>
                <value>
                    <fullName>AMARIS</fullName>
                </value>
                <value>
                    <fullName>AMARIS 500E/Compact</fullName>
                </value>
                <value>
                    <fullName>P200</fullName>
                </value>
                <value>
                    <fullName>200TX</fullName>
                </value>
                <value>
                    <fullName>Daytona</fullName>
                </value>
                <value>
                    <fullName>VX120</fullName>
                </value>
                <value>
                    <fullName>Keratron/Keratron Scout</fullName>
                </value>
                <value>
                    <fullName>Combi</fullName>
                </value>
                <value>
                    <fullName>Irx3</fullName>
                </value>
                <value>
                    <fullName>Sirius</fullName>
                </value>
                <value>
                    <fullName>AMARIS 750S</fullName>
                </value>
                <value>
                    <fullName>ESIRIS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>医院</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IDS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expireX1__c</fullName>
        <label>设备过保日期</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>possible__c</fullName>
        <label>可能性</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                </value>
                <value>
                    <fullName>0%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>阶段</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未启动</fullName>
                </value>
                <value>
                    <fullName>项目启动</fullName>
                    <default>true</default>
                    <label>项目启动</label>
                </value>
                <value>
                    <fullName>项目推进</fullName>
                </value>
                <value>
                    <fullName>项目谈判</fullName>
                </value>
                <value>
                    <fullName>合同签订中</fullName>
                </value>
                <value>
                    <fullName>已签合同</fullName>
                </value>
                <value>
                    <fullName>失去</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>推荐保修模式</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3年全保</fullName>
                    <default>true</default>
                    <label>3年全保</label>
                </value>
                <value>
                    <fullName>技术保修</fullName>
                </value>
                <value>
                    <fullName>1年全保</fullName>
                </value>
                <value>
                    <fullName>5年全保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>业务机会（技术用）</label>
    <nameField>
        <label>业务机会名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>业务机会（技术用）</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>customer__r.Name</formula>
        <label>#客户名字</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentname__c</fullName>
        <formula>product__r.Cname__c</formula>
        <label>#设备名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备使用状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>正常使用</fullName>
                    <default>true</default>
                    <label>正常使用</label>
                </value>
                <value>
                    <fullName>退换货</fullName>
                </value>
                <value>
                    <fullName>报废</fullName>
                </value>
                <value>
                    <fullName>停用</fullName>
                </value>
                <value>
                    <fullName>已销售</fullName>
                </value>
                <value>
                    <fullName>注册样机</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>chance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>业务机会</label>
        <referenceTo>chance__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>equVRbz</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>newwarrantyEnd__c</fullName>
        <label>设备最新保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>H1io</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WarrantyEndDate__c</fullName>
        <formula>ADDMONTHS(WarrantyStartDate__c,WarrantyPeriod__c)</formula>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <label>寄存销售</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/product__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>单价</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>类别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备</fullName>
                </value>
                <value>
                    <fullName>备件</fullName>
                </value>
                <value>
                    <fullName>耗材</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>#产品</label>
    <nameField>
        <label>产品编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Warrantyproduct__c.object
<CustomObject>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>Equipment__r.CustomerName__c</formula>
        <label>#客户名字</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>合约产品</relationshipLabel>
        <relationshipName>sBw2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>产品类别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>准分子设备</fullName>
                    <default>true</default>
                    <label>准分子设备</label>
                </value>
                <value>
                    <fullName>欧堡设备</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warrantyenddate__c</fullName>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <label>合约产品</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>合约产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Batch_Equipment_NewChance.cls
/**
*Create By:jmark
*TIME：2016年8月26日10:09:52
*Descripe:1、在设备对象中有字段设备保修终止日期，在此日期一年前自动生成新的业务机会，并邮件提醒。
          2、邮件提醒业务机会所有人，业务机会所有人=原设备所有人。
          3、设备对象下的相关列表有合约产品这一项，合约产品中有个字段叫保修结束日期。
                          现在的触发条件是：设备下如果关联有合约产品，以最新的合约产品的保修结束日期提前一年生成对应业务机会并邮件提醒；
                          如果没有，以设备对象的设备保修终止日期提前一年生成业务机会并邮件提醒。
 */
global class Batch_Equipment_NewChance implements Database.Batchable<SObject>{
      global Database.queryLocator start(Database.BatchableContext ctx)
     {
           system.debug('--------------------start');//查询出所有满足条件的设备记录
           return Database.getQueryLocator([select OwnerId,Owner.Email,Name,CustomerName__c,Equipmentname__c,warrantyEnd__c,product__c,product__r.Name,customer__c from Equipment__c]); 
     }
     global void execute(Database.BatchableContext ctx, list<Equipment__c> list_equ)
     {
           list<Warrantyproduct__c> list_war = [select Warrantyenddate__c,Equipment__c from Warrantyproduct__c where  Equipment__c in: list_equ and Warrantyenddate__c != null order by Warrantyenddate__c desc];
           map<Id,Warrantyproduct__c> map_war = new map<Id,Warrantyproduct__c>();
           system.debug('list_warlist_warlist_war'+list_war);
           if(list_war.size() > 0)
           {
               for(Warrantyproduct__c war:list_war)
               {
                   if(!map_war.containsKey(war.Equipment__c))
                   {
                       map_war.put(war.Equipment__c,war);
                   }
               }
           }
           system.debug('map_warmap_warmap_war'+map_war);
           Date now=Date.today();
           RecordType rt=[Select r.Name, r.Id From RecordType r where Name='保修销售'  and sobjecttype = 'chance__c'];
           for(Equipment__c eq:list_equ)
           {
               Date enddate = null;
               if(map_war.containsKey(eq.Id))
               {
                   enddate = map_war.get(eq.Id).Warrantyenddate__c;
                   //eq.newwarrantyEnd__c = map_war.get(eq.Id).Warrantyenddate__c;
               }
               else
               {
                   if(eq.warrantyEnd__c != null)
                   enddate = eq.warrantyEnd__c;
                   //eq.newwarrantyEnd__c = eq.warrantyEnd__c;
               }
               if(enddate != null)
               {
                   Integer days = now.daysBetween(enddate);
                   if(days == 365)//相隔一年，新建业务机会，发送邮件。
                   {
                       chance__c chance=new chance__c(); 
                       String strname=now.addYears(1).year()+'-'+eq.CustomerName__c+'-'+eq.product__r.Name+'-保修合约机会';
                       chance.Name=strname;
                       chance.customer__c=eq.customer__c;
                       chance.RecordTypeId=rt.Id;
                       chance.X1__c = eq.product__r.Name;
                       chance.expireX1__c=enddate;
                       chance.type__c='3年全保';
                       chance.Field1__c=500000;
                       chance.OwnerId=eq.OwnerId;
                       chance.stage__c='未启动';
                       chance.possible__c='30%';
                       insert chance;
                       if(eq.Owner.Email != null)
                       {
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            String[] toAddresses = new String[]{eq.Owner.Email};
                            mail.setToAddresses(toAddresses);
                            mail.setCharset('UTF-8'); 
                            mail.setUseSignature(false);
                            mail.setSubject(chance.Name); 
                            String str='尊敬的用户：<br/><br/>&nbsp;&nbsp;您好！现在'+eq.CustomerName__c+'的'+eq.Equipmentname__c+eq.Name+'的设备保修即将在'+String.valueOf(enddate)
                            +'到期，系统已自动生成新的保修业务机会，请您尽快处理。<br/>设备链接地址'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+eq.Id+'<br/>业务机会链接地址：'+URL.getSalesforceBaseUrl().toExternalForm()+'/'+chance.Id;
                            mail.setHtmlBody(str); 
                            Messaging.Sendemailresult[] r1=Messaging.sendEmail(new Messaging.Singleemailmessage[]{mail}); 
                       }
                   }
               }
           }
          // update list_equ;
     }
     global void finish(Database.BatchableContext ctx)
     {
                
     }
}