src/objects/chance__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>保修项目报价</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OwnEmail__c</fullName>
        <formula>Owner:User.Email</formula>
        <label>#所有人邮箱</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>医院</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IDS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>expireX1__c</fullName>
        <label>设备过保日期</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>possible__c</fullName>
        <label>可能性</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                </value>
                <value>
                    <fullName>0%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>stage__c</fullName>
        <label>阶段</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>未启动</fullName>
                </value>
                <value>
                    <fullName>项目启动</fullName>
                    <default>true</default>
                    <label>项目启动</label>
                </value>
                <value>
                    <fullName>项目推进</fullName>
                </value>
                <value>
                    <fullName>项目谈判</fullName>
                </value>
                <value>
                    <fullName>合同签订中</fullName>
                </value>
                <value>
                    <fullName>已签合同</fullName>
                </value>
                <value>
                    <fullName>失去</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>推荐保修模式</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3年全保</fullName>
                    <default>true</default>
                    <label>3年全保</label>
                </value>
                <value>
                    <fullName>技术保修</fullName>
                </value>
                <value>
                    <fullName>1年全保</fullName>
                </value>
                <value>
                    <fullName>5年全保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>业务机会（技术用）</label>
    <nameField>
        <label>业务机会名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>业务机会（技术用）</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>customer__r.Name</formula>
        <label>#客户名字</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentname__c</fullName>
        <formula>product__r.Cname__c</formula>
        <label>#设备名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>设备使用状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>正常使用</fullName>
                    <default>true</default>
                    <label>正常使用</label>
                </value>
                <value>
                    <fullName>退换货</fullName>
                </value>
                <value>
                    <fullName>报废</fullName>
                </value>
                <value>
                    <fullName>停用</fullName>
                </value>
                <value>
                    <fullName>已销售</fullName>
                </value>
                <value>
                    <fullName>注册样机</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>chance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>业务机会</label>
        <referenceTo>chance__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>equVRbz</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>H1io</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/product__c.object
<CustomObject>
    <fields>
        <fullName>Field1__c</fullName>
        <label>单价</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>类别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备</fullName>
                </value>
                <value>
                    <fullName>备件</fullName>
                </value>
                <value>
                    <fullName>耗材</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>#产品</label>
    <nameField>
        <label>产品编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>RoleName__c</fullName>
        <formula>UserRole.Name</formula>
        <label>#角色名</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Warrantyproduct__c.object
<CustomObject>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>Equipment__r.CustomerName__c</formula>
        <label>#客户名字</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>合约产品</relationshipLabel>
        <relationshipName>sBw2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field1__c</fullName>
        <label>产品类别</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>准分子设备</fullName>
                    <default>true</default>
                    <label>准分子设备</label>
                </value>
                <value>
                    <fullName>欧堡设备</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warrantyenddate__c</fullName>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <label>合约产品</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>合约产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cls_SchedulWarrantyproductBatch.cls
/**
*Create By:jmark
*TIME：2015年2月28日09:32:41
*Descripe:设备合约产品在保修到期前3个月，自动生成业务机会。并邮件发给：武总、陈经理、主管、高级助理
 */
global class Cls_SchedulWarrantyproductBatch implements Database.Batchable<SObject>{
      global Database.queryLocator start(Database.BatchableContext ctx)
     {
           system.debug('--------------------start');//查询出所有满足条件的合约产品记录
           return Database.getQueryLocator([select Warrantyenddate__c,Equipment__c from Warrantyproduct__c where  Warrantyenddate__c > NEXT_MONTH]); 
     }
     global void execute(Database.BatchableContext ctx, list<Warrantyproduct__c> list_war)
     {
         if(list_war != null && list_war.size()>0)
         {
             Date now=Date.today();
             set<Id> set_equ=new set<Id>();
             for(Warrantyproduct__c war:list_war)
             {
                 if(war.Warrantyenddate__c != null)
                    {
                         Integer months=now.monthsBetween(war.Warrantyenddate__c);
                         system.debug('--------------------months'+months);
                         if(months == 3)
                         {
                             set_equ.add(war.Equipment__c);//保修到期前3个月条件加入集合
                         }
                    } 
             }
             if(set_equ.size()>0)
             {
                 list<Equipment__c> list_req=[select OwnerId,Name,CustomerName__c,Equipmentname__c,warrantyEnd__c,product__c,customer__c from Equipment__c where Id in:set_equ];
                 set<Id> set_user=new set<Id>();//设备上的所有人ID
                 map<Id,Id> map_id=new map<Id,Id>();//用户存放用户对应的主管
                 if(list_req != null && list_req.size()>0)
                 {
                       for(Equipment__c req:list_req)
                       {
                           set_user.add(req.OwnerId);
                       }
                       list<User> list_user=new list<User>();
                       if(set_user.size()>0)
                       {
                           set<String> set_role=new set<String>();
                           set_role.add('021301-北京工程师');
                           set_role.add('021401-上海工程师');
                           set_role.add('021501-广州高级工程师');
                           set_role.add('021502-广州工程师');
                           list_user=[select Id,RoleName__c,ManagerId from User where Id in:set_user];
                           if(list_user.size()>0)
                           {
                              for(User u:list_user)
                              {
                                  if(!map_id.containsKey(u.Id))
                                  {
                                      if(set_role.contains(u.RoleName__c))
                                      {
                                          map_id.put(u.Id,u.ManagerId);
                                      }
                                      else
                                      {
                                          map_id.put(u.Id,u.Id);
                                      }
                                  }
                              }
                           }
                       }
                       system.debug('--------------------map_id'+map_id);
                       Set<String> str_email=new Set<String>();//处理需要发送邮件的邮箱
                       UserRole ur=[Select Name,Id From UserRole where Name='0211-高级助理'];
                       list<User> list_user1=[select Email from user where UserRoleId=:ur.Id];
                       if(list_user1 != null && list_user1.size()>0)//添加高级助理的电子邮件
                       {
                             for(User u:list_user1)
                             {
                                 if(u.Email != null)
                                 {
                                     if(!str_email.contains(u.Email))
                                     {
                                         str_email.add(u.Email);
                                     }
                                 }
                             }
                        }
                       RecordType rt=[Select r.Name, r.Id From RecordType r where Name='保修销售' and sobjecttype = 'chance__c'];
                       for(Equipment__c eq:list_req)
                       {
                           chance__c chance=new chance__c();
                           String strname=eq.CustomerName__c+now.year()+'保修合约机会';
                           chance.Name=strname;
                           chance.customer__c=eq.customer__c;
                           chance.RecordTypeId=rt.Id;
                           chance.OwnerId=map_id.get(eq.OwnerId);
                           chance.stage__c='预期';
                           chance.possible__c='10%';
                           chance.expireX1__c=eq.warrantyEnd__c;
                           chance.type__c='3年全保';
                           chance.Field1__c=500000;
                           insert chance;
                           system.debug('---------------------chance.Id'+chance.Id);
                           if(!str_email.contains(chance.OwnEmail__c) && chance.OwnEmail__c != null)
                           {
                                 str_email.add(chance.OwnEmail__c);
                           }
                           if(str_email.size()>0)
                           {
                                String[] stremail=new String[str_email.size()];
                                Integer i=0;
                                for(String s:str_email)
                                {
                                   stremail[i]=s;
                                   i++;
                                }
                                //新建邮件发送
                                system.debug('--------------------str_email'+str_email);
                                Messaging.Singleemailmessage email=new Messaging.Singleemailmessage();
                                email.setToAddresses(stremail);
                                system.debug('---------------------chance.Name'+chance.Name); 
                                email.setSubject(chance.Name); 
                                String str='尊敬的用户：<br/><br/>&nbsp;&nbsp;您好！现在'+eq.CustomerName__c+'的'+eq.Equipmentname__c+eq.Name+'的设备保修合约即将在'+String.valueOf(eq.warrantyEnd__c)
                                +'到期，系统已自动生成新的保修业务机会，请您尽快处理。<br/>设备链接地址：https://ap1.salesforce.com/'+eq.Id+'<br/>业务机会链接地址：https://ap1.salesforce.com/'+chance.Id;
                                email.setHtmlBody(str); 
                                Messaging.Sendemailresult[] r1=Messaging.sendEmail(new Messaging.Singleemailmessage[]{email}); 
                           }
                       }
                 }
             }
             
         }
     }
     global void finish(Database.BatchableContext ctx)
     {
                
      }
}