src/objects/ConfigurationList__c.object
<CustomObject>
    <fields>
        <fullName>configurationList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>库存名称</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ConfigurationList__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>库存</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ConfigurationList__c</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>configurationList2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>订单</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>order23</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>配置单/报价单</label>
    <nameField>
        <displayFormat>PZD-{YYYYMMDD}-{000000000}</displayFormat>
        <label>配置单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>配置单/报价单</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestConfig.cls
@isTest(SeeAlldata=true)
public class TestConfig {
    static testMethod void myUnitTest() {
        
        //
        Product2 newCkdj2 = [select Id, name from product2 limit 1];
        PriceBookEntry newPriceBookEntry = [select id, Pricebook2Id from PriceBookEntry where product2Id = :newCkdj2 .id and CurrencyIsoCode = 'CNY' limit 1];
        
       Account newAccount = new Account(Name = '测试客户For');
        insert newAccount;
        
        
        
        
        Order newOrder = new Order();   
        newOrder.Name = 'test Order';
        newOrder.AccountId = newAccount.Id;
        newOrder.EffectiveDate = date.today();
        newOrder.Status = 'Draft';
        newOrder.Pricebook2Id = newPriceBookEntry.Pricebook2Id;
        //newOrder.Id = ExportOrder.order__c;
        insert newOrder;
        //
        
        String currentConfigId = '';
        
        ConfigurationList__c config=new ConfigurationList__c();
        //config.Name='test1';
        Id configListRecordTypeId = Schema.SObjectType.ConfigurationList__c.getRecordTypeInfosByName().get('库存').getRecordTypeId();
        config.RecordTypeId = configListRecordTypeId;
        config.order__c = newOrder.Id;
        insert config;
        
        ApexPages.StandardController sc=new ApexPages.StandardController(config);
        NewConfigrationList ncl=new NewConfigrationList(sc);
        currentConfigId=sc.getId();
        
        
        
        
        
    }
}