src/objects/ConfigurationList__c.object
<CustomObject>
    <fields>
        <fullName>ContractReview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>合同预审表</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>ContractReviewHT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportuniy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>业务机会</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SynchronizationContract__c</fullName>
        <defaultValue>(&quot;否&quot;)</defaultValue>
        <label>是否同步到合同预审</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>否</fullName>
                </value>
                <value>
                    <fullName>是</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>configurationList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>库存名称</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ConfigurationList__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>库存</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ConfigurationList__c</referenceTo>
        <relationshipLabel>配置单/报价单</relationshipLabel>
        <relationshipName>configurationList2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>配置单/报价单</label>
    <nameField>
        <displayFormat>PZD-{YYYYMMDD}-{000000000}</displayFormat>
        <label>配置单编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>配置单/报价单</pluralLabel>
    <recordTypes>
        <fullName>ConfigurationList</fullName>
        <active>true</active>
        <label>配置单-大型</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ContractCharacter__c</fullName>
        <label>合同性质</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>内贸</fullName>
                </value>
                <value>
                    <fullName>外贸</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>销售机会名称</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>合同</relationshipLabel>
        <relationshipName>Opportunity1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WarrantyPeriod__c</fullName>
        <label>保修期（月）</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessSource__c</fullName>
        <label>商机来源</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>专家推荐</fullName>
                </value>
                <value>
                    <fullName>学术会议</fullName>
                </value>
                <value>
                    <fullName>主动拜访</fullName>
                </value>
                <value>
                    <fullName>渠道</fullName>
                </value>
                <value>
                    <fullName>内部交流</fullName>
                </value>
                <value>
                    <fullName>网路信息</fullName>
                </value>
                <value>
                    <fullName>同行交流</fullName>
                </value>
                <value>
                    <fullName>竞品预警</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                    <label>线索池</label>
                </value>
                <value>
                    <fullName>客户资产</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FinalCustomer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>最终用户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>销售机会</relationshipLabel>
        <relationshipName>FinalCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProcurementMethod__c</fullName>
        <label>采购方式</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>院内采购</fullName>
                </value>
                <value>
                    <fullName>招投标</fullName>
                </value>
                <value>
                    <fullName>融资租赁</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContractFinalNameTriggerTest.cls
@isTest
private class ContractFinalNameTriggerTest 
{

    @istest(SeeAlldata=true)
    static void testContractFinalNameTrigger ()
    {
    Account acc = new Account();
    acc.Name = 'll';
    insert acc ;
    
    Opportunity  opp = new Opportunity();
    opp.Name = 'pp';
    Opp.Name = '1';
    Opp.AccountId = acc.Id;
    Opp.FinalCustomer__c = acc.Id;
    Opp.StageName = '潜在阶段';
    Opp.ProcurementMethod__c = '院内采购';
    Opp.BusinessSource__c = '专家推荐';
    Opp.CloseDate = date.today();
    insert opp ;
    
    Contract  co = new Contract();
    co.AccountId = acc.Id ;
    co.Opportunity__c = Opp.id;
    co.WarrantyPeriod__c = 2 ;
    co.ContractCharacter__c ='内贸';
    insert co ;
    
    ConfigurationList__c configurationlist = new ConfigurationList__c();
    //configurationlist.OwnerId = '0056F0000082F6LQAU';
    //configurationlist.Name = '333';
    configurationlist.CurrencyIsoCode = 'CNY';
    //configurationlist.RecordTypeId = '0126F000001UVaNQAW';
    configurationlist.Opportuniy__c = opp.Id;
    configurationlist.ContractReview__c = co.Id;
    configurationlist.SynchronizationContract__c = '是';
    insert configurationlist;
    update co;   
       
     }
}