src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>department__c</fullName>
        <label>科室</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>眼科</fullName>
                </value>
                <value>
                    <fullName>院长室</fullName>
                </value>
                <value>
                    <fullName>设备科</fullName>
                </value>
                <value>
                    <fullName>耗材科</fullName>
                </value>
                <value>
                    <fullName>采购部</fullName>
                </value>
                <value>
                    <fullName>集团</fullName>
                </value>
                <value>
                    <fullName>财务科</fullName>
                </value>
                <value>
                    <fullName>医工科</fullName>
                </value>
                <value>
                    <fullName>器械科</fullName>
                </value>
                <value>
                    <fullName>物资部</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>landline__c</fullName>
        <label>座机</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <label>手机</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentname__c</fullName>
        <formula>product__r.Cname__c</formula>
        <label>#设备名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentunittype__c</fullName>
        <formula>product__r.SpecificationType__c</formula>
        <label>#设备型号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>hfmj__c</fullName>
        <label>能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnm__c</fullName>
        <label>能量测试HF（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hvv__c</fullName>
        <label>能量测试HV（V）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfmj__c</fullName>
        <label>能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnm__c</fullName>
        <label>能量测试LF（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/installreport__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicereport__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentname__c</fullName>
        <formula>servicereport__r.Equipmentname__c</formula>
        <label>设备名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentunittype__c</fullName>
        <formula>servicereport__r.Equipmentunittype__c</formula>
        <label>设备型号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>address__c</fullName>
        <formula>servicereport__r.customer__r.address__c</formula>
        <label>地址</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>arrivaldate__c</fullName>
        <label>到达日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>completedate__c</fullName>
        <label>完成日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <formula>servicereport__r.customer__r.Name</formula>
        <label>客户名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>department__c</fullName>
        <formula>TEXT(person__r.department__c)</formula>
        <label>负责科室</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>hfmj__c</fullName>
        <label>能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnm__c</fullName>
        <label>能量测试HF（nm）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>humidity__c</fullName>
        <label>安装环境湿度</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20%-29%</fullName>
                </value>
                <value>
                    <fullName>30%-45%</fullName>
                    <default>true</default>
                    <label>30%-45%</label>
                </value>
                <value>
                    <fullName>46%-55%</fullName>
                </value>
                <value>
                    <fullName>56%-65%</fullName>
                </value>
                <value>
                    <fullName>66%以上</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hvv__c</fullName>
        <label>能量测试HV（V）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>initialpressure__c</fullName>
        <label>气体参数/气瓶初始气压（Bar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>intracavitypressure__c</fullName>
        <label>腔内气压（Bar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>landline__c</fullName>
        <formula>person__r.landline__c</formula>
        <label>座机</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lfmj__c</fullName>
        <label>能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnm__c</fullName>
        <label>能量测试LF（nm）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>oniz</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <formula>person__r.phone__c</formula>
        <label>手机</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postcode__c</fullName>
        <formula>servicereport__r.customer__r.postcode__c</formula>
        <label>邮编</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>servicereport__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipName>OPhL</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>temperature__c</fullName>
        <label>安装环境温度</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>18℃-24℃</fullName>
                    <default>true</default>
                    <label>18℃-24℃</label>
                </value>
                <value>
                    <fullName>25℃-28℃</fullName>
                </value>
                <value>
                    <fullName>29℃以上</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>traincase__c</fullName>
        <label>设备培训情况</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备操作</fullName>
                </value>
                <value>
                    <fullName>设备基本维护</fullName>
                </value>
                <value>
                    <fullName>设备使用安全</fullName>
                </value>
                <value>
                    <fullName>注意事项</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>安装确认单</label>
    <nameField>
        <displayFormat>I-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>安装确认单</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>附属设备、欧堡安装确认单</description>
        <label>附属设备、欧堡</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Equipmentname__c</fullName>
        <formula>Equipment__r.Equipmentname__c</formula>
        <label>设备名称</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipmentunittype__c</fullName>
        <formula>Equipment__r.Equipmentunittype__c</formula>
        <label>设备型号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>address__c</fullName>
        <formula>customer__r.address__c</formula>
        <label>地址</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>department__c</fullName>
        <formula>TEXT(person__r.department__c)</formula>
        <label>负责科室</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>landline__c</fullName>
        <formula>person__r.landline__c</formula>
        <label>座机</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>oll6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>phone__c</fullName>
        <formula>person__r.MobilePhone</formula>
        <label>手机</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>postcode__c</fullName>
        <formula>customer__r.postcode__c</formula>
        <label>邮编</label>
        <type>Text</type>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Ctr_CreatePDF_InstallReport.cls
/**
*Dis: 设备安装报告在关闭时，可以生成打印模板，并自动发送报告附件邮件到第一责任人邮箱中 
*Time:2015年3月4日10:55:46
*Author:Somnus Wang
**/
public  class Ctr_CreatePDF_InstallReport {
	public Wrapper wrapp{get;set;}
	public String pageId{get;set;}
	public  Ctr_CreatePDF_InstallReport(){
	  wrapp=new Wrapper();
	  
	  Set<ID> setrecordtype=new Set<ID>();//安装确认单记录类型
	  Set<ID> setowner=new Set<ID>();//所有人
	  
	  String msg=null;//安装确认单记录类型
	  String u=null;//所有人
	  
	  //获得页面id   
	  pageId=ApexPages.currentPage().getParameters().get('id');
	  List<installreport__c> listinstallreport=[select Name,Id,RecordTypeId,customer__c,address__c,postcode__c,
	  department__c,person__r.Name,landline__c,phone__c,Equipmentname__c,Equipmentunittype__c,
	  Equipment__c,temperature__c,hfnm__c,hfmj__c,lfnm__c,lfmj__c,	hvv__c,humidity__c,initialpressure__c,intracavitypressure__c,
	  traincase__c,servicereport__r.OwnerId,arrivaldate__c,completedate__c from installreport__c where id=:pageId];
	  
	  for(installreport__c insta:listinstallreport){
		  setowner.add(insta.servicereport__r.OwnerId);//所有人
		  setrecordtype.add(insta.RecordTypeId);//安装确认单记录类型
		  System.debug('培训情况。。。。。。。'+insta.traincase__c);
		}
		
     List<RecordType> listrecordtype=[select Name from RecordType where Id in:setrecordtype];//安装确认单记录类型
	 List<User> users=[select Name from User where Id in:setowner];//查询所有人
	 
	 for(User uu:users){
			u=uu.Name;
		}
	 for(RecordType re:listrecordtype){
		System.debug('记录类型。。。。。。。。。。'+re.Name);
			if(re.Name!=null){
		     msg=re.Name;
			}
		}
		
		
	  for(installreport__c install:listinstallreport){
	   System.debug('安装环境温度...'+install.temperature__c+'安装环境湿度....'+install.humidity__c);
	        wrapp.types=msg;//记录类型
		    wrapp.hospitalName=install.customer__c;//医院名称
		    wrapp.address=install.address__c;//地    址
		    wrapp.postCode=install.postcode__c;//邮编
		    wrapp.department=install.department__c;//使用科室
		    wrapp.contacts=install.person__r.Name;//联系人
		    wrapp.landline=install.landline__c;//座机
		    wrapp.phone=install.phone__c;//手机
		    wrapp.equipmentname=install.Equipmentname__c;//设备名称
		    wrapp.equipmentunittype=install.Equipmentunittype__c;//型号
		    wrapp.equipment=install.Equipment__c;//序列号
		    wrapp.temperature=install.temperature__c;//安装环境温度
		    wrapp.humidity=install.humidity__c;//安装环境湿度
		    wrapp.hfnm=install.hfnm__c;//能量测试HF（nm）
		    wrapp.hfmj=install.hfmj__c;//能量测试HF（mj）
		    wrapp.lfnm=install.lfnm__c;//能量测试LF（nm）
		    wrapp.lfmj=install.lfmj__c;//能量测试LF（mj）
		    wrapp.hvv=install.hvv__c;//能量测试LV（v）
		    wrapp.initialpressure=install.initialpressure__c;//气体参数/气瓶初始气压
		    wrapp.intracavitypressure=install.intracavitypressure__c;//腔内气压
		    wrapp.traincase=install.traincase__c;//设备培训情况
		    wrapp.installengnineer=u;////安装工程师
		    if(install.arrivaldate__c!=null){
		    wrapp.arrivaldate=install.arrivaldate__c.year()+'-'+install.arrivaldate__c.month()+'-'+install.arrivaldate__c.day();//完成日期
		    }
		    if(install.completedate__c!=null){
		    wrapp.completedate=install.completedate__c.year()+'-'+install.completedate__c.month()+'-'+install.completedate__c.day();//到达日期
		    }
	  }
	 
	}
	public class Wrapper{
		
	  public String types {get;set;}//记录类型
	  public String hospitalName {get;set;}//医院名称
	  public String address {get;set;}//地    址
	  public String postCode {get;set;}//邮编
	  public String department {get;set;}//使用科室
	  public String contacts {get;set;}//联系人
	  public String landline {get;set;}//座机
	  public String phone {get;set;}//手机
	  public String equipmentname {get;set;}//设备名称
	  public String equipmentunittype {get;set;}//型号
	  public String equipment {get;set;}//序列号
	  public String temperature {get;set;}//安装环境温度
	  public String humidity {get;set;}//安装环境湿度
	  public Double hfnm {get;set;}//能量测试HF（nm）
	  public Double hfmj{get;set;}//能量测试HF（mj）
	  public Double lfnm{get;set;}//能量测试LF（nm）
	  public Double lfmj{get;set;}//能量测试LF（mj）
	  public Double hvv{get;set;}//能量测试LV（v）
	  public Double initialpressure {get;set;}//气体参数/气瓶初始气压
	  public Double intracavitypressure {get;set;}//腔内气压
	  public String traincase {get;set;}//设备培训情况
	  public String installengnineer {get;set;}//安装工程师
	  public String arrivaldate {get;set;}//到达日期
	  public String completedate {get;set;}//完成日期
	} 
}