src/objects/CustomObject22__c.object
<CustomObject>
    <fields>
        <fullName>InmarsatSerial05__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号5</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountName__c</field>
                <operation>equals</operation>
                <valueField>Equipment__c.customer__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号5)</relationshipLabel>
        <relationshipName>sb5gWO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InmarsatSerial06__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号6</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号6)</relationshipLabel>
        <relationshipName>sb5gWn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InmarsatSerial07__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号7</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号7)</relationshipLabel>
        <relationshipName>sb5gX7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InmarsatSerial08__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号8</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号8)</relationshipLabel>
        <relationshipName>sb5gXq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InmarsatSerial09__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号9</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号9)</relationshipLabel>
        <relationshipName>sb5gY0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InmarsatSerial10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号10</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>保修合同 (设备序列号10)</relationshipLabel>
        <relationshipName>sb5gZD</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>保修合同</label>
    <nameField>
        <displayFormat>BXHT{00000000}</displayFormat>
        <label>保修合同编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>保修合同</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>常规产品名称</label>
        <referenceTo>Product3__c</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>Kzi8</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product3__c.object
<CustomObject>
    <description>用于产品配置单</description>
    <label>产品（配置单产品）</label>
    <nameField>
        <label>物料名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品（配置单产品）</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrintTriggerTest.cls
@isTest
private class PrintTriggerTest 
{

    @istest(SeeAlldata=true)
    static void testPrintTrigger()
    {
         Product3__c  Pro5  = new Product3__c();
         Pro5.Name ='5';
         insert Pro5 ;
         Product3__c  Pro6  = new Product3__c();
         Pro6.Name ='6';
         insert Pro6 ;
         Product3__c  Pro7  = new Product3__c();
         Pro7.Name ='7';
         insert Pro7 ;
         Product3__c  Pro8  = new Product3__c();
         Pro8.Name ='8';
         insert Pro8 ;
         Product3__c  Pro9  = new Product3__c();
         Pro9.Name ='9';
         insert Pro9 ;
         Product3__c  Pro10  = new Product3__c();
         Pro10.Name ='10';
         insert Pro10 ;
         
         Equipment__c  Eq5 = new Equipment__c();
         Eq5.Name = '5'; 
         Eq5.ProductS__c = Pro5.id ;
         insert Eq5 ; 
         Equipment__c  Eq6 = new Equipment__c();
         Eq6.Name = '6'; 
         Eq6.ProductS__c = Pro6.id ;
         insert Eq6 ; 
         Equipment__c  Eq7 = new Equipment__c();
         Eq7.Name = '7'; 
         Eq7.ProductS__c = Pro7.id ;
         insert Eq7 ; 
         Equipment__c  Eq8 = new Equipment__c();
         Eq8.Name = '8'; 
         Eq8.ProductS__c = Pro8.id ;
         insert Eq8 ; 
         Equipment__c  Eq9 = new Equipment__c();
         Eq9.Name = '9'; 
         Eq9.ProductS__c = Pro9.id ;
         insert Eq9 ; 
         Equipment__c  Eq10 = new Equipment__c();
         Eq10.Name = '10'; 
         Eq10.ProductS__c = Pro10.id ;
         insert Eq10 ; 
         
         CustomObject22__c  Cus5  = new CustomObject22__c() ;
         Cus5.InmarsatSerial05__c = Eq5.Id ;
         Cus5.InmarsatSerial06__c = Eq6.Id ;
         Cus5.InmarsatSerial07__c = Eq7.Id ;
         Cus5.InmarsatSerial08__c = Eq8.Id ;
         Cus5.InmarsatSerial09__c = Eq9.Id ;
         Cus5.InmarsatSerial10__c = Eq10.Id ;
         insert Cus5 ;
    
    }
}