src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>installationdate__c</fullName>
        <label>安装日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>machineage__c</fullName>
        <label>机龄</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cls_EquipmentBatch.cls
/**
*Create By:jmark
*TIME：2015年2月27日09:13:53
*Descripe:自动计算设备机龄
 */
global class Cls_EquipmentBatch implements Database.Batchable<SObject>{
      global Database.queryLocator start(Database.BatchableContext ctx)
     {
     	   system.debug('--------------------start');
           return Database.getQueryLocator([select installationdate__c,machineage__c,Name from Equipment__c]); 
     }
     global void execute(Database.BatchableContext ctx, List<Equipment__c> list_equ)
     {
     	 system.debug('--------------------execute');
         if(list_equ != null && list_equ.size()>0)
	     {
	     	 Date now=Date.today();
	         for(Equipment__c eq:list_equ)
	         {
	             if(eq.installationdate__c != null)
	             {
	             	system.debug('--------------------now='+now);
	                 if(eq.installationdate__c <= now)
	                 {
	                     Integer daynum=eq.installationdate__c.daysBetween(now);
	                     Double year= Math.round(daynum/365.0*10)/10.0;
	                     system.debug('--------------------year='+year);
	                     system.debug('--------------------Name='+eq.Name);
	                     eq.machineage__c=year;
	                 }
	                 else
	                 {
	                     eq.machineage__c=null;
	                 }
	             }
	         }
	         Database.update(list_equ, false);  
	     }           
     }
     global void finish(Database.BatchableContext ctx)
     {
                
      }
}