src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>CustomerGrade__c</fullName>
        <formula>TEXT(customer__r.clientlevel__c)</formula>
        <label>#客户等级</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CustomerName__c</fullName>
        <formula>customer__r.Name</formula>
        <label>#客户名字</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnManage__c</fullName>
        <formula>Owner:User.Manager.Id</formula>
        <label>#所有人经理</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WhetherCreatePolling__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>勾选后根据保修开始日期和保修结束日期自动生成巡检记录</inlineHelpText>
        <label>是否生成巡检</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>设备</relationshipLabel>
        <relationshipName>obSe</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantySatart__c</fullName>
        <inlineHelpText>第一次装机后，根据验收时间自动默认保修开始日期</inlineHelpText>
        <label>设备保修开始日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantytype__c</fullName>
        <label>保修类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>设备合同-保修</fullName>
                    <default>true</default>
                    <label>设备合同-保修</label>
                </value>
                <value>
                    <fullName>售后合同-全保</fullName>
                </value>
                <value>
                    <fullName>售后合同-技术保</fullName>
                </value>
                <value>
                    <fullName>售后合同-单次服务</fullName>
                </value>
                <value>
                    <fullName>样机试用</fullName>
                </value>
                <value>
                    <fullName>保外</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
                <value>
                    <fullName>售后合同-半保</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>approvestate__c</fullName>
        <label>出差审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                </value>
                <value>
                    <fullName>审批中</fullName>
                    <default>true</default>
                    <label>审批中</label>
                </value>
                <value>
                    <fullName>审批结束</fullName>
                </value>
                <value>
                    <fullName>拒绝</fullName>
                </value>
                <value>
                    <fullName>调回</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>FtY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>secondperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>第二责任人</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EBhx</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>case状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Field2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>未响应</fullName>
                </value>
                <value>
                    <fullName>已响应</fullName>
                    <default>true</default>
                    <label>已响应</label>
                </value>
                <value>
                    <fullName>服务中</fullName>
                </value>
                <value>
                    <fullName>等待备件</fullName>
                </value>
                <value>
                    <fullName>未解决，观察中</fullName>
                </value>
                <value>
                    <fullName>已解决，继续观察</fullName>
                </value>
                <value>
                    <fullName>关闭</fullName>
                </value>
                <value>
                    <fullName>安装调试中</fullName>
                </value>
                <value>
                    <fullName>已安装，未调试</fullName>
                </value>
                <value>
                    <fullName>已安装，等待PMMA测试结果</fullName>
                </value>
                <value>
                    <fullName>已安装，PMMA未通过</fullName>
                </value>
                <value>
                    <fullName>关闭（PMMA通过）</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cbl_Equipment_InsertRequest.cls
/**
*Create By:jmark
*TIME：2015年3月3日10:08:14
*Descripe:在保修期内，设备保修，全保设备，客户不是VIP时，
 *当设备手动选择生成巡检复选框时，按3个月为间隔在保修期限内生成若干条巡检记录。
 *如果是Vip客户的设备，当设备手动选择生成巡检复选框时，按1个月为间隔在保修期限内生成若干条巡检记录。
 */
public class Cbl_Equipment_InsertRequest {
	  //新建设备记录时
      public void insertRequest(list<Equipment__c> list_equ)
      {
      	   list<Equipment__c> list_req=new list<Equipment__c>();
           for(Equipment__c equ:list_equ)
           {
               if(equ.WhetherCreatePolling__c == true && equ.warrantytype__c == '全保')
               {
                   list_req.add(equ);
               }
           }
           if(list_req.size()>0)
           {
           	   RecordType retp=[Select r.Id From RecordType r where Name='巡检'];
               for(Equipment__c equ:list_req)
               {
               	   Date startdate=equ.warrantySatart__c;
               	   Date enddate=equ.warrantyEnd__c;
               	   Integer days=startdate.daysBetween(enddate);
               	   Integer months=days/30;
               	   system.debug('=====================months'+months);
               	   list<servicerequest__c> list_ser=new list<servicerequest__c>();
               	   if(months>0)
               	   {
	               	   if(equ.CustomerGrade__c == '公司VIP')
	                   {
	                        for(Integer i=1;i<=months;i++)
	                        {
	                            servicerequest__c serv=new servicerequest__c();
	                            serv.RecordTypeId=retp.Id;
	                            serv.Name=equ.CustomerName__c+'巡检-'+String.valueOf(startdate.addDays(30*i));
	                            serv.requesttime__c=startdate.addDays(30*i);
	                            serv.customer__c=equ.customer__c;
	                            serv.Equipment__c=equ.Id;
	                            serv.state__c='服务中';
	                            serv.secondperson__c=equ.OwnManage__c;
	                            serv.approvestate__c='草稿';
	                            list_ser.add(serv);
	                        }
	                   }
	                   else
	                   {
	                         for(Integer i=1;i*3<=months;i++)
	                        {
	                            servicerequest__c serv=new servicerequest__c();
	                            serv.RecordTypeId=retp.Id;
	                            serv.Name=equ.CustomerName__c+'巡检-'+String.valueOf(startdate.addDays(30*i*3));
	                            serv.requesttime__c=startdate.addDays(30*i*3);
	                            serv.customer__c=equ.customer__c;
	                            serv.Equipment__c=equ.Id;
	                            serv.state__c='服务中';
	                            serv.secondperson__c=equ.OwnManage__c;
	                            serv.approvestate__c='草稿';
	                            list_ser.add(serv);
	                        }
	                   }
	                   insert list_ser;
               	   }
                   
               }
           }
      }
      //更新设备记录时
      public void updateRequest(list<Equipment__c> list_equ,map<Id,Equipment__c> map_equ)
      {
      	  list<Equipment__c> list_req=new list<Equipment__c>();
          for(Equipment__c equ:list_equ)
      	  {
      	       if(map_equ.get(equ.Id).WhetherCreatePolling__c == false && equ.WhetherCreatePolling__c == true )
	           {
	               list_req.add(equ);
	           }
      	  }
      	  if(list_req.size()>0)
      	  {
      	       insertRequest(list_req);
      	  }
      }
      //更新设备记录时阻止选定已经生成巡检的记录在次生成
      public void stopRequest(list<Equipment__c> list_equ,map<Id,Equipment__c> map_equ)
      {
      	  for(Equipment__c equ:list_equ)
      	  {
      	       if(map_equ.get(equ.Id).WhetherCreatePolling__c == true && equ.WhetherCreatePolling__c == false )
	           {
	               equ.addError('生成巡检复选框一经选定不可修改');
	           }
      	  }
          
      }
}