src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>installationdate__c</fullName>
        <label>安装日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>machineage__c</fullName>
        <label>机龄</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cbl_Equipment_time.cls
/**
*Create By:jmark
*TIME：2015年3月3日09:22:19
*Descripe:新建保存或更新时计算机龄
 */
public class Cbl_Equipment_time {
	//新建时
     public void insertTime(list<Equipment__c> list_equ)
     {
     	 Date now=Date.today();
         for(Equipment__c equ:list_equ)
         {
             if(equ.installationdate__c != null)
             {
                 if(equ.installationdate__c <=now)
                 {
                 	 
                     Integer daynum=equ.installationdate__c.daysBetween(now);
                     Double year= Math.round(daynum/365.0*10)/10.0;
                     system.debug('------------------year'+year);
                     equ.machineage__c=year;
                 }else
                 {
                     equ.machineage__c=null;
                 }
             }
         }
     }
     //更新时
     public void updateTime(list<Equipment__c> list_equ,map<Id,Equipment__c> map_equ)
     {
     	 list<Equipment__c> list_req=new list<Equipment__c>();
         for(Equipment__c equ:list_equ)
         {
             if(equ.installationdate__c != map_equ.get(equ.Id).installationdate__c)
             {
                 list_req.add(equ);
             }
         }
         if(list_req.size()>0)
         {
            insertTime(list_req);
         }
     }
}