src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstpressure__c</fullName>
        <label>初级气压(Bar)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfmj__c</fullName>
        <label>能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnm__c</fullName>
        <label>能量测试HF（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hvv__c</fullName>
        <label>能量测试HV（V）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lasernum__c</fullName>
        <label>激光腔脉冲数（M）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfmj__c</fullName>
        <label>能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnm__c</fullName>
        <label>能量测试LF（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nlvsmj__c</fullName>
        <label>最大能量950v10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>otherpressure__c</fullName>
        <label>次级气压(mBar)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zdnlvsmj__c</fullName>
        <label>最大能量1000V/1400v10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/servicereport__c.object
<CustomObject>
    <fields>
        <fullName>EquId__c</fullName>
        <formula>servicerequest__r.Equipment__c</formula>
        <label>#设备Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicerequest__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>firstpressure__c</fullName>
        <label>初始初级气压（Bar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>firstpressureend__c</fullName>
        <label>最终初级气压（Bar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfmj__c</fullName>
        <label>初始能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfmjend__c</fullName>
        <label>最终能量测试HF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnm__c</fullName>
        <label>初始能量测试HE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hfnmend__c</fullName>
        <label>最终能量测试HE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hvv__c</fullName>
        <label>初始能量测试HV（V）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>hvvend__c</fullName>
        <label>最终能量测试HV（V）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lasernum__c</fullName>
        <label>初始激光腔脉冲数（M）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lasernumend__c</fullName>
        <label>最终激光腔脉冲数（M）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfmj__c</fullName>
        <label>初始能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfmjend__c</fullName>
        <label>最终能量测试LF（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnm__c</fullName>
        <label>初始能量测试LE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>lfnmend__c</fullName>
        <label>最终能量测试LE（nm）</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nlvsmj__c</fullName>
        <label>初始最大能量950v10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nlvsmjend__c</fullName>
        <label>最终最大能量950v10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>otherpressure__c</fullName>
        <label>初始次级气压（mBar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>otherpressureend__c</fullName>
        <label>最终次级气压（mBar）</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zdnlvsmj__c</fullName>
        <label>初始最大能量1000V(Mlase)1400v(EXSO)10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>zdnlvsmjend__c</fullName>
        <label>最终最大能量1000v(Mlase）1400v（EXSO)10s下（mj）</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>技术服务报告</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>技术服务报告</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cbl_servicereport_renew.cls
/**
*Create By:jmark
*TIME：2015年2月26日10:35:25
*Descripe:设备参数更新
 */
public class Cbl_servicereport_renew {
	//新建技术服务报告更新设备参数
     public void insertRenewEquipment(list<servicereport__c> list_ser)
     {
     	 set<String> set_Id=new set<String>();
         for(servicereport__c ser:list_ser)
         {
            if(ser.EquId__c != null)
            {
                set_Id.add(ser.EquId__c);
            }
         }
         list<Equipment__c> list_equ=new list<Equipment__c>();
         if(set_Id.size()>0)
         {
            list_equ=[select Id,firstpressure__c,otherpressure__c,lasernum__c,
            hfmj__c,hfnm__c,hvv__c,lfmj__c,lfnm__c,zdnlvsmj__c,nlvsmj__c from Equipment__c where Id in:set_Id];
         }
         if(list_equ.size()>0)
         {
             for(servicereport__c ser:list_ser)
	         {
	            for(Equipment__c equ:list_equ)
	            {
	                if(ser.EquId__c == equ.Id)
	                {
	                   equ.firstpressure__c=ser.firstpressureend__c;
	                   equ.otherpressure__c=ser.otherpressureend__c;
	                   equ.lasernum__c=ser.lasernumend__c;
	                   equ.hfmj__c=ser.hfmjend__c;
	                   equ.hfnm__c=ser.hfnmend__c;
	                   equ.hvv__c=ser.hvvend__c;
	                   equ.lfmj__c=ser.lfmjend__c;
	                   equ.lfnm__c=ser.lfnmend__c;
	                   equ.zdnlvsmj__c=ser.zdnlvsmjend__c;
	                   equ.nlvsmj__c=ser.nlvsmjend__c;
	                }
	            }
	         }
	         update list_equ;
         }
     }
     //更新技术服务报告更新设备参数
     public void updateRenewEquipment(list<servicereport__c> list_ser,map<Id,servicereport__c> map_ser)
     {
         
     }
}