src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warrantyEnd__c</fullName>
        <label>设备保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>warrantySatart__c</fullName>
        <inlineHelpText>第一次装机后，根据验收时间自动默认保修开始日期</inlineHelpText>
        <label>设备保修开始日期</label>
        <type>Date</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>请求时间</label>
        <type>Date</type>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/sparepart__c.object
<CustomObject>
    <fields>
        <fullName>WarrantyEnd__c</fullName>
        <formula>Field2__r.warrantyEnd__c</formula>
        <label>保修终止日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Whetherthewarrantyperiod__c</fullName>
        <label>#是否在保修期内</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requesttime__c</fullName>
        <label>计划使用时间或要求到货时间</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>备件申请</relationshipLabel>
        <relationshipName>OPjC</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>备件申请</label>
    <nameField>
        <displayFormat>BJSQ-{YYYY}{MM}-{00000000}</displayFormat>
        <label>申请编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>备件申请</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Warrantyproduct__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>设备序列号</label>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>合约产品</relationshipLabel>
        <relationshipName>sBw2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warrantyenddate__c</fullName>
        <label>保修结束日期</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warrantystartdate__c</fullName>
        <label>保修开始日期</label>
        <type>Date</type>
    </fields>
    <label>合约产品</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>合约产品</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cbl_sparepart_whetherperiod.cls
/**
*Create By:jmark
*TIME：2015年3月4日15:24:23
*Descripe:新建备件申请时，判断是否在保修期内
 */
public class Cbl_sparepart_whetherperiod {
	//新建记录时
    public void insertWhetherPeriod(list<sparepart__c> list_spa)
    {
        for(sparepart__c spa:list_spa)
        {
            //判断是否在设备合同保修期内
            servicerequest__c ser=[select requesttime__c,Equipment__c,Equipment__r.warrantySatart__c,Equipment__r.warrantyEnd__c from servicerequest__c where Id=:spa.servicerequest__c];
            if(ser.Equipment__r.warrantySatart__c != null && ser.Equipment__r.warrantyEnd__c != null)
            {
                 if(ser.requesttime__c >= ser.Equipment__r.warrantySatart__c && ser.requesttime__c <= ser.Equipment__r.warrantyEnd__c)
                 {
                     spa.Whetherthewarrantyperiod__c='是';
                 }
                 else
                 {
                     spa.Whetherthewarrantyperiod__c='否';
                 }
            }
            //判断是否在产品合约保修期内
            list<Warrantyproduct__c> list_war=[select Warrantystartdate__c,Warrantyenddate__c from Warrantyproduct__c where Equipment__c = :ser.Equipment__c];
            if(list_war != null && list_war.size()>0)
            {
                for(Warrantyproduct__c war:list_war)
                {
                    if(war.Warrantystartdate__c != null && war.Warrantyenddate__c != null)
                    {
                         if(ser.requesttime__c >= war.Warrantystartdate__c && ser.requesttime__c <= war.Warrantyenddate__c)
		                 {
		                     spa.Whetherthewarrantyperiod__c='是';
		                 }
                    }
                }
            }
        }
    }
}