src/objects/Equipment__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>设备名称</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>warrantySatart__c</fullName>
        <inlineHelpText>第一次装机后，根据验收时间自动默认保修开始日期</inlineHelpText>
        <label>设备保修开始日期</label>
        <type>Date</type>
    </fields>
    <label>设备</label>
    <nameField>
        <label>设备序列号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>设备</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/installreport__c.object
<CustomObject>
    <fields>
        <fullName>EquId__c</fullName>
        <formula>servicereport__r.Equipment__r.Id</formula>
        <label>#设备Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicereport__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>receptiontime__c</fullName>
        <label>验收时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>servicereport__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipName>OPhL</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>安装确认单</label>
    <nameField>
        <displayFormat>I-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>安装确认单</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>附属设备、欧堡安装确认单</description>
        <label>附属设备、欧堡</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicereport__c.object
<CustomObject>
    <fields>
        <fullName>EquId__c</fullName>
        <formula>servicerequest__r.Equipment__c</formula>
        <label>#设备Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <formula>servicerequest__r.Equipment__r.Name</formula>
        <label>设备序列号</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>receptiontime__c</fullName>
        <label>验收时间</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>servicerequest__c</fullName>
        <label>服务请求</label>
        <referenceTo>servicerequest__c</referenceTo>
        <relationshipLabel>技术服务报告</relationshipLabel>
        <relationshipName>OPhB</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>技术服务报告</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>技术服务报告</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录角膜/全眼设备</description>
        <label>准分子检查设备</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/servicerequest__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>设备序列号</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>设备必须属于客户</errorMessage>
            <filterItems>
                <field>Equipment__c.customer__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.customer__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Equipment__c</referenceTo>
        <relationshipLabel>服务请求</relationshipLabel>
        <relationshipName>sBwg</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>服务请求</label>
    <nameField>
        <label>请求名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>服务请求</pluralLabel>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>用于记录巡检类型的服务请求</description>
        <label>巡检</label>
    </recordTypes>
    <recordTypes>
        <fullName>htaz</fullName>
        <active>true</active>
        <description>用于记录合同新机安装类型的服务请求</description>
        <label>合同安装</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Cbl_installreport_time.cls
/**
*Create By:jmark
*TIME：2015年2月26日13:20:39
*Descripe:新机安装后进行的PMMA测试证书时间自动关联到设备基础信息下的保修开始时间
 */
public class Cbl_installreport_time {
      //新建安装确认单时
      public void insertInstallreportTime(list<installreport__c> list_ins)
      {
           set<Id> set_Equipment=new set<Id>();//装设备ID
           set<Id> set_servicerequest=new set<Id>();//装服务请求ID
           list<installreport__c> list_req=new list<installreport__c>();//装满足条件的安装确认单
           for(installreport__c ins:list_ins)
           {
               if(ins.receptiontime__c != null)
               {
                   set_servicerequest.add(ins.servicereport__c);
               }
           }
           system.debug('------------------set_servicerequest'+set_servicerequest);
           set<Id> set_request=new set<Id>();//装符合条件服务请求ID
           list<servicerequest__c> list_ser=new list<servicerequest__c>();
           list<RecordType> listrtp=[Select r.Name, r.Id,r.developername From RecordType r where r.developername='htaz']; 
           if(set_servicerequest.size()>0)//查询出满足条件的服务请求
           {
               list_ser=[select Id,RecordTypeId from servicerequest__c where Id in:set_servicerequest];
           }
           if(list_ser.size()>0)
           {
               for(servicerequest__c ser:list_ser)//判断满足记录类型为新机安装
               {
                  if(ser.RecordTypeId == listrtp[0].Id)
                  {
                      set_request.add(ser.Id);
                  }
               }
           }
           if(set_request.size()>0)
           {
               for(installreport__c ins:list_ins)//获取是新机安装的安装确认单记录
	           {
	               for(Id id:set_request)
	               {
	                   if(ins.servicereport__c == id)
	                   {
	                       list_req.add(ins);
	                       set_Equipment.add(ins.EquId__c);
	                   }
	               }
	           }
	           list<Equipment__c> list_equ=new list<Equipment__c>();
	           if(set_Equipment.size()>0)//取出符合条件的设备记录
	           {
	               list_equ=[select Id,warrantySatart__c from Equipment__c where Id in:set_Equipment];
	           }
	           system.debug('------------------list_equ'+list_equ);
	           if(list_equ.size()>0 && list_req.size()>0)//给符合条件的设备记录赋值
	           {
	               for(Equipment__c equ:list_equ)
	               {
	                   for(installreport__c ins:list_req)
	                   {
	                       if(equ.Id == ins.EquId__c)
	                       {
	                          equ.warrantySatart__c=ins.receptiontime__c;
	                       }
	                   }
	               }
	               update list_equ;
	           }
           }
      }
      //更新安装确认单时
      public void updateInstallreportTime(list<installreport__c> list_ins,map<Id,installreport__c> map_ins)
      {
           list<installreport__c> list_req=new list<installreport__c>();
           for(installreport__c ins:list_ins)
           {
               if(ins.receptiontime__c != map_ins.get(ins.Id).receptiontime__c)
               {
                   list_req.add(ins);
               }
           }
           if(list_req.size()>0)
           {
               insertInstallreportTime(list_req);
           }
      }
}