src/objects/ExtendedOrder__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>延保订单</relationshipLabel>
        <relationshipName>AccountName</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>延保订单</label>
    <nameField>
        <displayFormat>YBDD-{YYYY}{MM}-{0000000}</displayFormat>
        <label>延保订单名称</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>延保订单</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SalesWeeklyReport__c.object
<CustomObject>
    <label>销售周报</label>
    <nameField>
        <displayFormat>SR-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>销售周报 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>销售周报</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WorkPlan__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>客户名称</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Plan</relationshipLabel>
        <relationshipName>Work_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <description>对应Event上的ActivityDate(标准字段)</description>
        <label>ActivityDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ActivityDescription__c</fullName>
        <label>活动描述</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>销售活动ID</description>
        <label>ActivityId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>备注</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompletionStatus__c</fullName>
        <label>完成状态</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>已完成</fullName>
                </value>
                <value>
                    <fullName>未完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NeedSupport__c</fullName>
        <label>需要支持</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityActivityTheme__c</fullName>
        <label>销售活动类型</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesWeeklyReport__c</fullName>
        <label>销售周报</label>
        <referenceTo>SalesWeeklyReport__c</referenceTo>
        <relationshipLabel>工作计划</relationshipLabel>
        <relationshipName>Work_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>活动主题</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>类型</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>本周</fullName>
                </value>
                <value>
                    <fullName>下周</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WeekChinese__c</fullName>
        <label>日期</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>星期一</fullName>
                </value>
                <value>
                    <fullName>星期二</fullName>
                </value>
                <value>
                    <fullName>星期三</fullName>
                </value>
                <value>
                    <fullName>星期四</fullName>
                </value>
                <value>
                    <fullName>星期五</fullName>
                </value>
                <value>
                    <fullName>星期六</fullName>
                </value>
                <value>
                    <fullName>星期日</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>联系人</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Work Plan</relationshipLabel>
        <relationshipName>Work_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>工作情况</label>
    <nameField>
        <label>工作情况 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkPlanThisWeek.cls
public class WorkPlanThisWeek{
    
    
    public List<WorkPlan__c>  AllEvents {set;get;}
    
    String weeklyReportId = '';
    public WorkPlanThisWeek(ApexPages.StandardController controller) {
        weeklyReportId = controller.getId();
        AllEvents =  [select OpportunityActivityTheme__c,Comment__c,ActivityId__c,ActivityDate__c,CompletionStatus__c,CreatedDate,AccountName__c,AccountName__r.name,WeekChinese__c,Subject__c,ActivityDescription__c,contact__c,contact__r.name,NeedSupport__c from WorkPlan__c where Type__c = '本周' and SalesWeeklyReport__c = :weeklyReportId order by createddate];
        for(WorkPlan__c  wp : AllEvents){
           // Datetime dt = wp.CreatedDate.addHours(8);
            //system.debug('dt :'+ dt);
           // String weekDay = number2MonthName.get(dt.formatGmt('EEE'));
            //wp.ActivityDate__c=     ;
            //system.debug('ev.WeekDay__c :'+ ev.WeekDay__c );
        }
    }
    public static Map<String, String> number2MonthName = new Map<String, String>
        {
            'Mon' => '星期一',
            'Tue' => '星期二',
            'Wed' => '星期三',
            'Thu' => '星期四',
            'Fri' => '星期五',
            'Sat' => '星期六',
            'Sun' => '星期日'
            
        }; 
}