src/objects/IntermediateTable__c.object
<CustomObject>
    <fields>
        <fullName>ConventionalClosingStage__c</fullName>
        <label>常规成交阶段总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <externalId>true</externalId>
        <label>唯一值</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LargEuropeanAuctionStage__c</fullName>
        <label>大型欧堡成交阶段金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LargeOBAmount__c</fullName>
        <label>大型欧堡预计成交总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LargeOpportunityAmount2__c</fullName>
        <label>大型销售机会总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LargeQGAmount__c</fullName>
        <label>大型屈光预计成交总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LargeRefractivePhase__c</fullName>
        <label>大型屈光成交阶段金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RuleAmount__c</fullName>
        <label>常规预计成交总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RuleOpportunityAmount__c</fullName>
        <label>常规销售机会总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalOpportunityAmount__c</fullName>
        <label>整体销售机会总金额</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>年份</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>中间表对象</label>
    <nameField>
        <label>中间表对象名称</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>中间表对象</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BusinessOpportunityApprovalStatus__c</fullName>
        <label>销售机会审批状态</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>草稿</fullName>
                    <default>true</default>
                    <label>草稿</label>
                </value>
                <value>
                    <fullName>待审批</fullName>
                </value>
                <value>
                    <fullName>已审批</fullName>
                </value>
                <value>
                    <fullName>已拒绝</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClosedDateYear__c</fullName>
        <formula>YEAR( CloseDate )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>预计成交日期年份</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SalesOpportunityStatus__c</fullName>
        <label>销售机会关闭状态</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>丢单</fullName>
                </value>
                <value>
                    <fullName>中断</fullName>
                </value>
                <value>
                    <fullName>赢单</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalAmount__c</fullName>
        <label>预计成交总金额（元）</label>
        <summarizedField>CustomObject18__c.TotalMoney__c</summarizedField>
        <summaryFilterItems>
            <field>CustomObject18__c.State__c</field>
            <operation>notEqual</operation>
            <value>丢单, 中断</value>
        </summaryFilterItems>
        <summaryForeignKey>CustomObject18__c.Field1__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>year__c</fullName>
        <formula>YEAR(   DATEVALUE(CreatedDate)       )  -  YEAR( TODAY() )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>是否为本年</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduleSyncAmount2.cls
global class ScheduleSyncAmount2 implements Schedulable{
    
    //public static String CRON_EXP = '0 0 17 * *？';


    global void execute(SchedulableContext sc) {
        String  Key  =  date.today().year()+'.'+date.today().month();
        IntermediateTable__c currentIntermediateTable = new IntermediateTable__c();
        try
        {
            currentIntermediateTable = [select LargeOBAmount__c,RuleAmount__c,LargeQGAmount__c,Year__c,TotalOpportunityAmount__c ,RuleOpportunityAmount__c,LargeRefractivePhase__c,LargEuropeanAuctionStage__c,ConventionalClosingStage__c  from IntermediateTable__c where  Key__c = :Key limit 1];
        
        }
        catch(Exception e)
        {   
            //如果没有查到数据的话，创建 一条本月度的数据。
            currentIntermediateTable = new IntermediateTable__c();
            currentIntermediateTable.Key__c = Key ; 
            currentIntermediateTable.Name =  currentIntermediateTable.Key__c ;   
            insert currentIntermediateTable;
            currentIntermediateTable = [select LargeOpportunityAmount2__c ,LargeOBAmount__c,RuleAmount__c,LargeQGAmount__c,Year__c,TotalOpportunityAmount__c ,RuleOpportunityAmount__c,LargeRefractivePhase__c,LargEuropeanAuctionStage__c,ConventionalClosingStage__c  from IntermediateTable__c where  Key__c = :Key limit 1];
        }
        
         Decimal totalAmount  = 0 ;  
        // 计算所有销售机会总金额
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  StageName != '潜在阶段'And BusinessOpportunityApprovalStatus__c ='已审批'  And ClosedDateYear__c = : currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断')]){
            totalAmount =  Decimal.valueof(String.valueOf(results.get('totalAmount'))); 
            system.debug('totalAmount :'+ totalAmount);   
        }
         
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();   
        currentIntermediateTable.TotalOpportunityAmount__c =  totalAmount ; 
        
        //计算所有常规销售机会总金额
        Decimal totalNormalAmount  = 0 ; 
        Id orderTypeIdC = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会').getRecordTypeId();
        Id orderTypeIdC1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdC OR RecordTypeId =:orderTypeIdC1) And StageName != '潜在阶段' And BusinessOpportunityApprovalStatus__c ='已审批' And ClosedDateYear__c = : currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断') ]){
            totalNormalAmount =  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.RuleOpportunityAmount__c =  totalNormalAmount ; 
        
        //计算所有大型销售机会总金额
        Decimal totalLargeOppAmount  = 0 ; 
        Id orderTypeIdJ = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会').getRecordTypeId();
        Id orderTypeIdJ1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会（大区经理)').getRecordTypeId();
        Id orderTypeIdJ2 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会').getRecordTypeId();
        Id orderTypeIdJ3 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdJ OR RecordTypeId =:orderTypeIdJ1 OR RecordTypeId =:orderTypeIdJ2 OR RecordTypeId =:orderTypeIdJ3) And StageName != '潜在阶段' And BusinessOpportunityApprovalStatus__c ='已审批' And ClosedDateYear__c = : currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断') ]){
            totalLargeOppAmount =  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.LargeOpportunityAmount2__c =  totalLargeOppAmount ; 

        //计算大型屈光预计成交总金额
        Decimal totalAmountLargeQGAmount  = 0 ; 
        Id orderTypeIdD = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会').getRecordTypeId();
        Id orderTypeIdD1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会（大区经理)').getRecordTypeId();
        
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdD OR RecordTypeId = :orderTypeIdD1) And StageName != '潜在阶段' And BusinessOpportunityApprovalStatus__c ='已审批' And ClosedDateYear__c = : currentIntermediateTable.Year__c ]){
            totalAmountLargeQGAmount=  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.LargeQGAmount__c=  totalAmountLargeQGAmount; 
        
        
        //计算大型欧堡预计成交总金额  
        Decimal totalAmountLargeOBAmount  = 0 ; 
        Id orderTypeIdE = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会').getRecordTypeId();
        Id orderTypeIdE1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdE OR RecordTypeId = :orderTypeIdE1) And StageName != '潜在阶段' And BusinessOpportunityApprovalStatus__c ='已审批'  And ClosedDateYear__c =: currentIntermediateTable.Year__c ]){
            totalAmountLargeOBAmount=  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.LargeOBAmount__c=  totalAmountLargeOBAmount; 
        
         //计算常规预计成交总金额  
        Decimal totalAmountRuleAmount  = 0 ; 
        Id orderTypeIdF = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会').getRecordTypeId();
        Id orderTypeIdF1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdE OR RecordTypeId = :orderTypeIdE1) And StageName != '潜在阶段' And BusinessOpportunityApprovalStatus__c ='已审批'  And ClosedDateYear__c = :currentIntermediateTable.Year__c ]){
            totalAmountRuleAmount=  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.RuleAmount__c=  totalAmountRuleAmount ; 

        //计算大型屈光成交阶段金额
        Decimal totalAmountLargeRefractivePhase  = 0 ; 
        Id orderTypeIdG  = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会').getRecordTypeId();
        Id orderTypeIdG1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型屈光销售机会（大区经理)').getRecordTypeId();
        
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdG OR RecordTypeId = :orderTypeIdG1) And StageName = '成交阶段' And BusinessOpportunityApprovalStatus__c ='已审批' And ClosedDateYear__c = : currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断') ]){
            totalAmountLargeRefractivePhase =  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.LargeRefractivePhase__c =  totalAmountLargeRefractivePhase ; 
        
        
        //计算大型欧堡成交阶段金额 
        Decimal totalAmountLargEuropeanAuctionStage  = 0 ; 
        Id orderTypeIdH = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会').getRecordTypeId();
        Id orderTypeIdH1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('大型欧堡销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdH OR RecordTypeId = :orderTypeIdH1) And StageName = '成交阶段' And BusinessOpportunityApprovalStatus__c ='已审批'  And ClosedDateYear__c =: currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断') ]){
            totalAmountLargEuropeanAuctionStage =  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.LargEuropeanAuctionStage__c=  totalAmountLargEuropeanAuctionStage; 
        
         //计算常规成交阶段总金额  
        Decimal totalAmountConventionalClosingStage  = 0 ; 
        Id orderTypeIdI = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会').getRecordTypeId();
        Id orderTypeIdI1 = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('常规销售机会（大区经理）').getRecordTypeId();
        for(AggregateResult results   : [select sum(TotalAmount__c) totalAmount from Opportunity where  (RecordTypeId = :orderTypeIdI OR RecordTypeId = :orderTypeIdI1) And StageName = '成交阶段' And BusinessOpportunityApprovalStatus__c ='已审批'  And ClosedDateYear__c = :currentIntermediateTable.Year__c And (SalesOpportunityStatus__c != '丢单' OR SalesOpportunityStatus__c != '中断') ]){
            totalAmountLargEuropeanAuctionStage =  Decimal.valueof(String.valueOf(results.get('totalAmount')));    
        }
        currentIntermediateTable.Key__c = date.today().year()+'.'+date.today().month();
        currentIntermediateTable.ConventionalClosingStage__c=  totalAmountConventionalClosingStage  ; 
        
        
        Database.upsert(currentIntermediateTable, IntermediateTable__c.Key__c);
        
    }
    
    global ScheduleSyncAmount2()
    {   
    }
    
}