src/objects/knowledgecontent__c.object
<CustomObject>
    <fields>
        <fullName>Is_published__c</fullName>
        <defaultValue>false</defaultValue>
        <label>是否发布</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>content__c</fullName>
        <label>解决方案</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>describe__c</fullName>
        <label>故障描述</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>keyword__c</fullName>
        <label>关键字</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>knowledgetype__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>故障类型</label>
        <referenceTo>knowledgetype__c</referenceTo>
        <relationshipLabel>知识库内容</relationshipLabel>
        <relationshipName>pZEP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>知识库内容</label>
    <nameField>
        <displayFormat>QA-{000000}</displayFormat>
        <label>Q&amp;A编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>知识库内容</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/knowledgetype__c.object
<CustomObject>
    <label>知识库类型</label>
    <nameField>
        <label>类型</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>知识库类型</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QAdetail.cls
/*
*Function:重写知识库的新建和编辑页面
*Date:2013-01-29
*/
public class QAdetail 
{
	public String strTypeId { get; set;}//类型ID
	//public String strTypeIdNew {get;set;}//从列表新建时取类型Id
	public String strMode { get; set;}//编辑 or 新建状态
	public knowledgecontent__c obj_QA{ get; set;} 

	public QAdetail(ApexPages.standardController controller)
	{
		strTypeId=ApexPages.currentPage().getParameters().get('tid');
		//strTypeIdNew=ApexPages.currentPage().getParameters().get('CF00N90000004QCNe_lkid');//00NN0000000UWYk
		Id id=ApexPages.currentPage().getParameters().get('Id');
		strMode=ApexPages.currentPage().getParameters().get('mode');
		if((strMode=='new'||strMode==null)&&id==null)
		{
			obj_QA=new knowledgecontent__c();
			obj_QA.knowledgetype__c=strTypeId;
			obj_QA.OwnerId = Userinfo.getUserId();
			//IsUsed__c			需要设置
		}else if((strMode=='edit'||strMode=='view'||strMode==null)&&id!=null)
		{
			obj_QA=[Select q.keyword__c, q.describe__c, q.knowledgetype__c, q.OwnerId, q.Name, q.LastModifiedDate, 
					q.Is_published__c, q.Id,q.content__c, 
					q.CreatedDate From knowledgecontent__c q where q.id=:id];
		}
	} 

	public PageReference back() 
	{
		Id id=ApexPages.currentPage().getParameters().get('Id');
		PageReference pagereference = null;
		if(strMode=='new')
		{
			pagereference=new PageReference('https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/QATree');
			pagereference.setRedirect(true);
		}else if(strMode==null)
		{
			if(id!=null)
			{
				pagereference=new PageReference('https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+id);
			}
		}
		return pagereference;
	}
	
	public PageReference save() 
	{
		upsert obj_QA;
		//PageReference pagereference=new PageReference('https://'+ApexPages.currentPage().getHeaders().get('Host')+'/apex/QAlist?tid='+obj_QA.QAType__c);
		
		PageReference pagereference=new PageReference('https://'+ApexPages.currentPage().getHeaders().get('Host')+'/'+obj_QA.Id);
		pagereference.setRedirect(true);
		return pagereference;
		
	}
	//测试类
	/*private static testMethod void myUnitTest() {
		knowledgetype__c qatype = new knowledgetype__c();
		qatype.Name = '珠宝';
		qatype.WhetherLowerType__c = true;
		insert qatype;
		knowledgecontent__c qa = new knowledgecontent__c();
		qa.Theme__c = 'test';
		qa.QAType__c = qatype.Id;
		qa.Description__c ='1222';
		insert qa;
		
		ApexPages.CurrentPage().getParameters().put('tid',qatype.Id);
		Apexpages.currentPage().getParameters().put('Id',qa.Id);
		Apexpages.currentPage().getParameters().put('mode','view');
		ApexPages.standardController controller= new Apexpages.standardController(qa);
		QAdetail qadetail = new QAdetail(controller);
		qadetail.save();
		qadetail.back();
		Apexpages.currentPage().getParameters().put('mode','new');
		ApexPages.standardController controller2= new Apexpages.standardController(qa);
		QAdetail qadetail2 = new QAdetail(controller2);
	}*/
}