src/objects/kucun__c.object
<CustomObject>
    <fields>
        <fullName>Field2__c</fullName>
        <formula>Field1__r.Cname__c</formula>
        <label>备件中文名称</label>
        <type>Text</type>
    </fields>
    <label>库存</label>
    <nameField>
        <displayFormat>SP-{00000000}</displayFormat>
        <label>库存</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>库存</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/outinstock__c.object
<CustomObject>
    <fields>
        <fullName>ckplace__c</fullName>
        <label>仓库地点</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>广州库</fullName>
                </value>
                <value>
                    <fullName>北京库</fullName>
                </value>
                <value>
                    <fullName>上海库</fullName>
                </value>
                <value>
                    <fullName>香港库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isquartify__c</fullName>
        <label>是否确认入库</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>否</fullName>
                    <default>true</default>
                    <label>否</label>
                </value>
                <value>
                    <fullName>是</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>number__c</fullName>
        <label>数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>出入库</relationshipLabel>
        <relationshipName>crk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态库</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>新品库</fullName>
                </value>
                <value>
                    <fullName>损耗库</fullName>
                </value>
                <value>
                    <fullName>备用机库</fullName>
                </value>
                <value>
                    <fullName>备用机损耗库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>出入库</label>
    <nameField>
        <displayFormat>K{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>编号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>出入库</pluralLabel>
    <recordTypes>
        <fullName>incangk</fullName>
        <active>true</active>
        <description>用于备件返还、手动入库</description>
        <label>入库</label>
    </recordTypes>
    <recordTypes>
        <fullName>outcangk</fullName>
        <active>true</active>
        <description>用于自动创建出库、手动出库</description>
        <label>出库</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/product__c.object
<CustomObject>
    <fields>
        <fullName>SpecificationType__c</fullName>
        <label>规格型号</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>#产品</label>
    <nameField>
        <label>产品编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>产品</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/stock__c.object
<CustomObject>
    <fields>
        <fullName>Field2__c</fullName>
        <label>库存</label>
        <referenceTo>kucun__c</referenceTo>
        <relationshipLabel>库存明细</relationshipLabel>
        <relationshipName>kucun</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProductNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>产品编号</label>
        <referenceTo>product__c</referenceTo>
        <relationshipName>GzBJ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>状态库</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>新品库</fullName>
                </value>
                <value>
                    <fullName>损耗库</fullName>
                </value>
                <value>
                    <fullName>备用机库</fullName>
                </value>
                <value>
                    <fullName>备用机损耗库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>virtualnum__c</fullName>
        <label>可用库存</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>warehouse__c</fullName>
        <label>仓库地点</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>北京库</fullName>
                </value>
                <value>
                    <fullName>上海库</fullName>
                </value>
                <value>
                    <fullName>广州库</fullName>
                </value>
                <value>
                    <fullName>香港库</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>xcnum__c</fullName>
        <label>现存数量</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>库存明细</label>
    <nameField>
        <label>库存编号</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>库存明细</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Cbl_outinstock_updatestock_Test.cls
/**
 * Creat By : Arvin
 * Time : 2015年2月28日
 * Describe: Cbl_outinstock_updatestock 的测试类
 */
@isTest(SeeAllData=true)
private class Cbl_outinstock_updatestock_Test 
{
    
    
    //测试插入新的出入库记录 
    static testMethod void Test_insertStock()
    {
        //出入库列表
        product__c pro = new product__c();
        pro.Name='test';
        insert pro;
        
        kucun__c kc=new kucun__c();
        //kc.Name='sth';
        insert kc;
        
        stock__c st=new stock__c();
        st.name='test001';
        st.state__c='新品库';
        st.warehouse__c='北京';
        st.ProductNumber__c=pro.id;
        st.virtualnum__c=10;
        st.xcnum__c=10;
        st.Field2__c=kc.Id;
        insert st;
        
        stock__c st1=new stock__c();
        st1.name='test001';
        st1.state__c='废品库';
        st1.warehouse__c='北京';
        st1.ProductNumber__c=pro.id;
        st1.virtualnum__c=10;
        st1.xcnum__c=10;
        st1.Field2__c=kc.Id;
        insert st1;
        
        RecordType RecordIncangk=[Select r.SobjectType, r.Id, r.DeveloperName 
        				From RecordType r 
        				where r.SobjectType='outinstock__c'
        				and r.DeveloperName='incangk'];
        RecordType RecordOutcangk=[Select r.SobjectType, r.Id, r.DeveloperName 
        				From RecordType r 
        				where r.SobjectType='outinstock__c'
        				and r.DeveloperName='outcangk'];
        //入库
        outinstock__c ins = new outinstock__c();
        pro.SpecificationType__c = 'AMARIS750';
        ins.product__c = pro.Id;
        ins.ckplace__c = '北京';
        ins.state__c = '新品库';
        ins.RecordTypeId=RecordIncangk.id;
        ins.isquartify__c='是';
        ins.number__c = 3;
       
       	try
       	{
       		insert ins;
       	}
       	catch(Exception e)
       	{
       		
       	}
        
        //出库
        outinstock__c outs = new outinstock__c();
        outs.product__c = pro.Id;
        outs.ckplace__c = '北京';
        outs.state__c = '新品库';
        outs.number__c = 2;
        outs.RecordTypeId=RecordOutcangk.id;
        insert outs;
        
        
         ins.number__c = 4;
         update ins;
         
        outs.number__c = 1;
        update outs;
        
        
        
        outs.state__c = '废品库';
        update outs;
        
        delete ins;
        delete outs;
    }
    
    //测试更改出入库记录
    static testMethod void Test_updateStock()
    {
    	
        //出入库列表
        product__c pro = new product__c();
        pro.Name='test';
        insert pro;
        
        kucun__c kc=new kucun__c();
        //kc.Name='sth';
        insert kc;
        
        stock__c st=new stock__c();
        st.name='test001';
        st.state__c='新品库';
        st.warehouse__c='北京';
        st.ProductNumber__c=pro.id;
        st.virtualnum__c=10;
        st.xcnum__c=10;
        st.Field2__c=kc.Id;
        insert st;
        
        stock__c st1=new stock__c();
        st1.name='test001';
        st1.state__c='废品库';
        st1.warehouse__c='北京';
        st1.ProductNumber__c=pro.id;
        st1.xcnum__c=10;
        st1.virtualnum__c=10;
        st1.Field2__c=kc.Id;
        insert st1;
        
        RecordType RecordIncangk=[Select r.SobjectType, r.Id, r.DeveloperName 
        				From RecordType r 
        				where r.SobjectType='outinstock__c'
        				and r.DeveloperName='incangk'];
        RecordType RecordOutcangk=[Select r.SobjectType, r.Id, r.DeveloperName 
        				From RecordType r 
        				where r.SobjectType='outinstock__c'
        				and r.DeveloperName='outcangk'];
        //入库
        outinstock__c ins = new outinstock__c();
        pro.SpecificationType__c = 'AMARIS750';
        ins.product__c = pro.Id;
        ins.ckplace__c = '北京';
        ins.state__c = '新品库';
        ins.RecordTypeId=RecordIncangk.id;
        ins.number__c = 3;
       
       	try
       	{
       		insert ins;
       	}
       	catch(Exception e)
       	{
       		
       	}
        
        //出库
        outinstock__c outs = new outinstock__c();
        outs.product__c = pro.Id;
        outs.ckplace__c = '北京';
        outs.state__c = '新品库';
        outs.number__c = 2;
        outs.RecordTypeId=RecordOutcangk.id;
        insert outs;
        
        
         ins.number__c = 4;
         update ins;
         
        outs.number__c = 1;
        update outs;
        
        ins.state__c = '废品库';
        update ins;
        
        outs.state__c = '废品库';
        update outs;
        
        delete ins;
        delete outs;
    
    }
    
    
}